### ISSUE TITLE
psql stuck on reconnection

### ISSUE THREAD

**Issue by hlinnaka** [neondatabase/neon#1449] opened 2022-03-31 19:07 UTC
To reproduce:

1. Connect with "quick connect:

```
$ psql -h start.zenith.tech
NOTICE:  ☀️  Welcome to Zenith!
To proceed with database creation, open the following link:

    https://console.zenith.tech/psql_session/4d754295011d1690

It needs to be done once and we will send you '.pgpass' file,
which will allow you to access or create databases without opening your web browser.
NOTICE:  Connecting to database.
psql (13.5 (Debian 13.5-0+deb11u1), server 14.2)
WARNING: psql major version 13, server major version 14.
         Some psql features might not work.
Type "help" for help.

heikki=>
```

2. Connect again, with the `\c` command

```
heikki=> \c
NOTICE:  ☀️  Welcome to Zenith!
To proceed with database creation, open the following link:

    https://console.zenith.tech/psql_session/712b63cd43e0b9b2

It needs to be done once and we will send you '.pgpass' file,
which will allow you to access or create databases without opening your web browser.
^C
^C^C
^C^C
```

Without opening the link, try killing psql with CTRL-C. It doesn't work. It does work in the first connection attempt, but when reconnecting with `\c` it does not.

**Comment by dhammika** [comment] 2022-03-31 23:11
> 
> Without opening the link, try killing psql with CTRL-C. It doesn't work. It does work in the first connection attempt, but when reconnecting with `\c` it does not.

Perhaps this is because psql keeps previous connection active while it reconnects with new params. Shows same behavior on direct connections to pg.

**Comment by dhammika** [comment] 2022-04-01 04:05
Actually first connection arms SIGINT handler, 
https://github.com/zenithdb/postgres/blob/1dc6535b877050a3b3768ca1ed140dd15a1a3e78/src/bin/psql/startup.c#L303
and second connection stays in sock poller waiting for ready-for-query (or error) response, 
https://github.com/zenithdb/postgres/blob/1dc6535b877050a3b3768ca1ed140dd15a1a3e78/src/interfaces/libpq/fe-misc.c#L1074-L1076

**Comment by hlinnaka** [comment] 2022-04-01 14:01
Hmm, I wonder if this is similar to https://github.com/zenithdb/zenith/issues/1213

**Comment by LizardWizzard** [comment] 2022-04-22 11:41
It worked for me. I think #1448 fixed it. @hlinnaka can you confirm that it works for you?

**Comment by hlinnaka** [comment] 2022-05-12 15:53
> It worked for me. I think #1448 fixed it. @hlinnaka can you confirm that it works for you?

I can still reproduce this. Might depend on the psql version, mine is:
```
$  psql --version
psql (PostgreSQL) 13.5 (Debian 13.5-0+deb11u1)
```
But I could also reproduce it with a version of psql built from Postgres master branch.

**Comment by dhammika** [comment] 2022-05-12 16:46
Can repro this by dropping traffic from pg for the auxiliary _query cancel_ connection and psql gets blocked on connect. Any connectivity issue will create similar results.

**Comment by shanyp** [comment] 2023-02-26 09:39
@vadim2404 not sure if this is still relevant, added compute label

**Comment by vadim2404** [comment] 2023-03-01 13:29
```
neondb=> \c
psql (14.7 (Homebrew), server 15.2)
WARNING: psql major version 14, server major version 15.
         Some psql features might not work.
SSL connection (protocol: TLSv1.3, cipher: TLS_AES_256_GCM_SHA384, bits: 256, compression: off)
You are now connected to database "neondb" as user "vadim".
neondb=> \c
psql (14.7 (Homebrew), server 15.2)
WARNING: psql major version 14, server major version 15.
         Some psql features might not work.
SSL connection (protocol: TLSv1.3, cipher: TLS_AES_256_GCM_SHA384, bits: 256, compression: off)
You are now connected to database "neondb" as user "vadim".
```

**Comment by hlinnaka** [comment] 2023-03-01 14:04
I can still reproduce this. Note that this is specifically related to the "link authentication", with `pg.neon.tech`.

**Comment by vadim2404** [comment] 2023-03-02 11:23
gotcha, didn't get this detail first

**Comment by kelvich** [comment] 2023-07-20 15:56
BTW, should we fix it in `psql`? I guess makes sense to exit on `Ctrl-C` in any state?

**Comment by hlinnaka** [comment] 2023-07-20 16:18
yep.

@tristan957, you've been looking into ctrl-c with pgbench, could you have a look at this too?

**Comment by tristan957** [comment] 2023-07-20 21:43
In a perfect world, I think the libpq interfaces should take the equivalent of Go's `context.Context`. Here is _a_ diff I came up with to restore the expected SIGINT behavior:

```patch
diff --git a/src/bin/psql/command.c b/src/bin/psql/command.c
index 6733f008fd..5a5e7d98b7 100644
--- a/src/bin/psql/command.c
+++ b/src/bin/psql/command.c
@@ -3532,6 +3532,8 @@ do_connect(enum trivalue reuse_previous_specification,
 		const char **values = pg_malloc((nconnopts + 1) * sizeof(*values));
 		int			paramnum = 0;
 		PQconninfoOption *ci;
+		struct sigaction oldact;
+		struct sigaction newact = { 0 };
 
 		/*
 		 * Copy non-default settings into the PQconnectdbParams parameter
@@ -3576,9 +3578,14 @@ do_connect(enum trivalue reuse_previous_specification,
 		keywords[paramnum] = NULL;
 		values[paramnum] = NULL;
 
+		newact.sa_handler = SIG_DFL;
+		sigaction(SIGINT, &newact, &oldact);
+
 		/* Note we do not want libpq to re-expand the dbname parameter */
 		n_conn = PQconnectdbParams(keywords, values, false);
 
+		sigaction(SIGINT, &oldact, NULL);
+
 		pg_free(keywords);
 		pg_free(values);
```

The intention of the patch is to use the default signal handler while within libpq. Then, when we get out of it, restore the psql signal handler. I have a feeling this patch doesn't work on Windows, though I am not even sure if this problem also reproduced on Windows.

The reason it works for the first db connection is that `setup_cancel_handler()` isn't called until after the first `PQconnectdbParams()`.

**Comment by tristan957** [comment] 2023-07-24 16:31
https://www.postgresql.org/message-id/CUAJJDVD8L61.2AH6VEEDMTXX3%40gonk

**Comment by conradludgate** [comment] 2024-01-31 12:56
Confirming I can still reproduce this. However, I don't think it's a concern for proxy so I'm removing the label

**Comment by tristan957** [comment] 2024-04-03 15:49
Committed today. I don't think it'll be back-patched, but available for PG 17.

**Closed by tristan957** 2024-04-03 15:49 UTC
Labels: t/bug
