### ISSUE TITLE
proxy: better error messages for postgres connection limits

### ISSUE THREAD

**Issue by conradludgate** [neondatabase/neon#5368] opened 2023-09-25 15:24 UTC
We have customers exhausting active connection limits of postgres. Errors include

1. `remaining connection slots are reserved for non-replication superuser connections`
2. `sorry, too many clients already`
3. `no more connections allowed (max_client_conn)`

All 3 mean similar things. 1 and 2 refer to the postgres connection limit. 3 refers to the pgbouncer connection limit.

All three should be prefixed with a consistent greppable error message. 1 and 2 should additionally include a suggestion to use pooled connections.

**Comment by bojanserafimov** [comment] 2023-09-25 16:15
It's not what I thought it was.

So the first error `remaining connection slots are reserved for non-replication superuser connections` comes from [here](https://github.com/neondatabase/postgres/blob/5d5cfee12783f0989a9c9fe13bb40b5585812568/src/backend/utils/init/postinit.c#L825), which is part of `InitPostgres`. So it deserves investigation.

The second error `sorry, too many clients already` comes from [here](https://github.com/neondatabase/postgres/blob/5d5cfee12783f0989a9c9fe13bb40b5585812568/src/backend/postmaster/postmaster.c#L2526), which is part of `ProcessStartupPacket`, which makes sense (this could be a legit client error).

The third error `no more connections allowed (max_client_conn)` I can't even find in the code, so idk where it's coming from.

**Comment by bojanserafimov** [comment] 2023-09-25 16:22
Wait it might actually be what I thought it was, explain by the comment [here](https://github.com/neondatabase/postgres/blob/5d5cfee12783f0989a9c9fe13bb40b5585812568/src/backend/postmaster/postmaster.c#L2517). Postgres is being optimistic that some connections won't need a backend because they won't auth. If they actually auth, we get error 1 later. If there's enough connections to cross the optimistic threshold, then we get error 2 early. We can double-check by reproducing the behavior locally

**Comment by bojanserafimov** [comment] 2023-09-25 16:29
To attempt to reproduce:
Test 1: Make enough connections to see error 1
Test 2: While already at the limit, make enough **concurrent** connection attempts to get error 2. Adding some sleeps during connection from the client-side can make it easier to trigger the behavior (if the error is what I think it is)

**Comment by conradludgate** [comment] 2023-09-25 17:46
> The third error no more connections allowed (max_client_conn) I can't even find in the code, so idk where it's coming from.

It's from PgBouncer, not Postgres

**Comment by conradludgate** [comment] 2023-09-25 17:57
> Wait it might actually be what I thought it was, explain by the comment [here](https://github.com/neondatabase/postgres/blob/5d5cfee12783f0989a9c9fe13bb40b5585812568/src/backend/postmaster/postmaster.c#L2517). Postgres is being optimistic that some connections won't need a backend because they won't auth. If they actually auth, we get error 1 later. If there's enough connections to cross the optimistic threshold, then we get error 2 early. We can double-check by reproducing the behavior locally

Ok. As far as I can tell then the action from the end user is the same in either case, right? They need to use less connections, get a larger DB, or use pooling

**Comment by stradig** [comment] 2024-02-27 09:29
Not actionable by proxy team, closing.

**Closed by stradig** 2024-02-27 09:29 UTC
Labels: c/cloud/proxy
