### ISSUE TITLE
test_lsn_lease_size flaky

### ISSUE THREAD

**Issue by skyzh** [neondatabase/neon#8293] opened 2024-07-05 19:27 UTC
https://neon-github-public-dev.s3.amazonaws.com/reports/pr-8291/9811816038/index.html#suites/d70040d097c5c7c438e421e0416d69ce/8b9d1e05e6c02925

```
AssertionError: assert 312497288 == 312316992 ± 3.3e+04
  comparison failed
  Obtained: 312497288
  Expected: 312316992 ± 3.3e+04
```

cc @yliang412 do you have any idea or I/we can look into it next week?

**Comment by yliang412** [comment] 2024-07-05 19:30
Tried to resolve by having a larger threshold in #8282, but I feel this won't fix the root cause.

**Closed** 2024-07-08 20:50 UTC
Labels: t/bug, c/storage/pageserver
