### ISSUE TITLE
AssertionError: current db Lsn should shoud not be less than the one stored on remote storage

### ISSUE THREAD

**Issue by hlinnaka** [neondatabase/neon#1707] opened 2022-05-16 09:24 UTC
Got a test failure in ci (https://app.circleci.com/pipelines/github/neondatabase/neon/6375/workflows/0f3074d5-ee3a-41c9-ad8d-cbac364c0655/jobs/63923/tests):
```
AssertionError: current db Lsn should shoud not be less than the one stored on remote storage
assert 23684648 >= 24002288
 +  where 23684648 = lsn_from_hex('0/1696628')
test_runner/batch_others/test_remote_storage.py:120: in test_remote_storage_backup_and_restore
    assert lsn_from_hex(detail['local']['last_record_lsn']) >= current_lsn, 'current db Lsn should shoud not be less than the one stored on remote storage'
E   AssertionError: current db Lsn should shoud not be less than the one stored on remote storage
E   assert 23684648 >= 24002288
E    +  where 23684648 = lsn_from_hex('0/1696628')
```

**Comment by hlinnaka** [comment] 2022-05-16 09:34
@SomeoneToIgnore can you investigate this, please?

**Comment by SomeoneToIgnore** [comment] 2022-05-16 10:50
Not entirely sure what happens here.

The panic is due to too big number, specified as `capacity` of the `HashMap` (~`usize::MAX/7`). We get it via `self.len()` inside `SyncQueue`.
I don't see how `self.len()` could underflow, since it's only managed internally. Might it be that we access it with `Ordering::Relaxed` badly?

**Comment by SomeoneToIgnore** [comment] 2022-05-17 04:45
Duplicate of https://github.com/neondatabase/neon/issues/1719

**Closed** 2022-05-17 04:46 UTC
