### ISSUE TITLE
flaky test: `test_neon_superuser` / pg15-release cannot properly exit when replication is enabled

### ISSUE THREAD

**Issue by skyzh** [neondatabase/neon#6969] opened 2024-02-29 15:04 UTC
## Steps to reproduce

In #6935 this test will randomly fail. Error messages captured by @knizhnik:

```
PG:2024-02-28 12:38:59.697 GMT [308398] LOG:  logical decoding found consistent point at 0/2A8DAF8
PG:2024-02-28 12:38:59.697 GMT [308398] DETAIL:  There are no running transactions.
PG:2024-02-28 12:38:59.697 GMT [308398] STATEMENT:  START_REPLICATION SLOT "pg_16426_sync_16423_7340631415576970097" LOGICAL 0/2A8DB30 (proto_version '3', publication_names '"pub"')
PG:2024-02-28 12:38:59.697 GMT [308398] LOG:  Drop replication slot pg_replslot/pg_16426_sync_16423_7340631415576970097
PG:2024-02-28 12:38:59.697 GMT [308398] STATEMENT:  DROP_REPLICATION_SLOT pg_16426_sync_16423_7340631415576970097 WAIT
PG:2024-02-28 12:39:00.198 GMT [308143] LOG:  received fast shutdown request
PG:2024-02-28 12:39:00.198 GMT [308143] LOG:  aborting any active transactions
PG:2024-02-28 12:39:00.198 GMT [308162] FATAL:  terminating connection due to administrator command
PG:2024-02-28 12:39:00.198 GMT [308152] FATAL:  terminating background worker "WAL proposer" due to administrator command
PG:2024-02-28 12:39:00.198 GMT [308151] FATAL:  terminating background worker "Logical replication monitor" due to administrator command
PG:2024-02-28 12:39:00.199 GMT [308143] LOG:  background worker "Logical replication monitor" (PID 308151) exited with exit code 1
PG:2024-02-28 12:39:00.199 GMT [308143] LOG:  background worker "WAL proposer" (PID 308152) exited with exit code 1
PG:2024-02-28 12:39:00.199 GMT [308143] LOG:  background worker "logical replication launcher" (PID 308153) exited with exit code 1
PG:2024-02-28 12:39:00.199 GMT [308146] LOG:  shutting down
2024-02-28T12:39:00.691236Z ERROR could not get backends state change: could not query backends: connection closed
2024-02-28T12:39:00.691249Z  WARN failed to get list of walsenders: Error { kind: Closed, cause: None }
```

## Logs, links
-

**Comment by skyzh** [comment] 2024-02-29 15:56
Take a quick look and this seems to be caused by the server cannot be shutdown when logical replication is enabled. Mostly failing in PG15. cc @save-buffer

**Comment by skyzh** [comment] 2024-02-29 15:58
Or not related to logical replication... sorry for tagging

**Comment by knizhnik** [comment] 2024-02-29 19:18
Why do we run monitor for CI tests at all?
It seems to be there only test when Neon is used as subscriber ion logical replication (in other tests vanilla Postgres is used).
We are suspending suspending (shutdown) of compute node if LR is active. Can it be the source of the problem: monitor prevents termination of subscriber node?

**Comment by skyzh** [comment] 2024-02-29 19:38
The problem is that postgres never exits. In `compute_ctl.rs`,

```
    // Wait for the child Postgres process forever. In this state Ctrl+C will
    // propagate to Postgres and it will be shut down as well.
    if let Some((mut pg, logs_handle)) = pg {
        // Startup is finished, exit the startup tracing span
        drop(startup_context_guard);

        let ecode = pg
            .wait()
            .expect("failed to start waiting on Postgres process");
        PG_PID.store(0, Ordering::SeqCst);
```


It's stuck at `pg.wait()`.

**Comment by skyzh** [comment] 2024-02-29 19:38
The monitor is working as expected. `compute_ctl` exits using `std::os::exit`, so everything will be terminated.

**Comment by andreasscherbaum** [comment] 2024-03-05 15:33
@skyzh Please add the details about the root cause.

This is realistically not a problem in production, until and unless we suspend compute with logical replication.

**Comment by skyzh** [comment] 2024-03-05 15:54
A summary on the root cause: If we have a replication job in pg15, it won't exit by itself. Postmaster waits forever.

This does not cause any problems for us in prod because we don't suspend the compute node if logical replication is enabled. If we really want to stop it, Kubernetes will (possibly) do a force kill on a timeout, and therefore it can always stop in prod.

The only problem is that stop may take <timeout> long time, and during this time, users cannot connect to the database.

Mitigation: https://github.com/neondatabase/neon/pull/6975 that closes the replication. This allows us to pass the test case.

If we need to solve this issue, we will need to look into our pg15 source code modification and how it correlates with this seemingly unrelated pull request. https://github.com/neondatabase/neon/pull/6935

**Comment by skyzh** [comment] 2024-03-18 18:12
the issue can be reproduced on pg14-debug and pg15-debug after inserting a few loggings into the postmaster process on macOS.

**Comment by skyzh** [comment] 2024-03-18 18:15
the process is stuck on WalSndWaitStopping

**Comment by skyzh** [comment] 2024-03-18 18:49
```
PG:2024-03-18 18:45:36.217 GMT [38518] LOG:  standby "walproposer" is now a synchronous standby with priority 1
PG:2024-03-18 18:45:38.939 GMT [38512] LOG:  still waiting walsnd=0, state=3, pid=38518
```

Okay, the problem seems to be with safekeepers. The walproposer does not exit when there is logical replications slots open.

**Comment by skyzh** [comment] 2024-03-18 19:09
It seems that safekeeper did not receive SIGUSR2 (got_SIGUSR2=false), and it does not exit. Signal handling in pg15 is different from other versions? (pg14 is just flaky, and sometimes it passes, not sure if the root cause is the same)

**Comment by arssher** [comment] 2024-03-19 04:57
Interesting, what is the best way to reproduce? " inserting a few loggings into the postmaster process on macOS." -- in which place? #6975 is merged, so it happens on main now, right?

**Comment by arssher** [comment] 2024-03-19 05:00
> This does not cause any problems for us in prod because we don't suspend the compute node if logical replication is enabled.

This ''don't suspend the compute node if logical replication is enabled" logic doesn't prevent stop once we actually decided to stop, i.e. SIGTERMed the postmaster, so issue here is something different.

**Comment by skyzh** [comment] 2024-03-19 14:26
@arssher remove the last SQL (drop replication) from `test_neon_superuser` and this seems to be stably reproduced on macOS.

This is the log mixed with my own printfs...

[compute.log](https://github.com/neondatabase/neon/files/14651931/compute.log)

**Closed** 2024-03-28 15:24 UTC
Labels: t/bug, c/storage/compute

**Comment by andreasscherbaum** [comment] 2024-04-03 15:09
Still in progress, to be releases this week.
