### ISSUE TITLE
No such file or directory errors reading layer files

### ISSUE THREAD

**Issue by hlinnaka** [neondatabase/neon#1751] opened 2022-05-19 09:32 UTC
This happened on the CI with the new test from PR #1735. I think we've seen this a few times before, but couldn't find an existing issue for it

https://app.circleci.com/pipelines/github/neondatabase/neon/6512/workflows/cb7bf6ab-11db-440c-88fa-3c704e9f6fca/jobs/65793/artifacts

```
2022-05-19T08:03:47.313535Z ERROR compact loop terminated with error: Failed to load delta layer /tmp/test_output/test_pageserver_chaos/repo/tenants/775a6bca9dcc4d5baf1db289176bbd7c/timelines/e3aa3049715941f858d26f6c42c375f6/000000067F000032AE000040000000003707-000000067F000032AE000040000000003792__000000001E7EFFE9-0000000021371F61
...
2022-05-19T08:03:49.189238Z  WARN could not remove ephemeral file '/tmp/test_output/test_pageserver_chaos/repo/tenants/775a6bca9dcc4d5baf1db289176bbd7c/timelines/e3aa3049715941f858d26f6c42c375f6/ephemeral-6': No such file or directory (os error 2)
2022-05-19T08:03:49.190033Z ERROR Thread 'layer flush thread' tenant_id: Some(775a6bca9dcc4d5baf1db289176bbd7c), timeline_id: Some(e3aa3049715941f858d26f6c42c375f6) exited with error: No such file or directory (os error 2)
```

_Originally posted by @hlinnaka in https://github.com/neondatabase/neon/issues/1735#issuecomment-1131463161_

**Comment by aome510** [comment] 2022-05-19 19:59
Trying to reproduce this issue locally, no result so far 😅 . A few notes when looking into this issue:

- Judging from the log, it seems that a delta L1 file is not found while that delta file's data is in the layer map
- I think this can happen either when (*)
 1. the file is GCed by a running thread and is read by another thread. The two threads belong to different page servers, so the layer maps are different
 2. something weird happens during the creation of the L1 layer, which creates the layer data in memory but not the actual L1 file. I suspect this can happen because the `DeltaLayerWriter` fails to rename the temp file.

1 is quite unlikely because I don't see any GC info from the logs. I tried to add some delays to the fsync and rename during the delta file creation, but haven't found anything.

(*): I wonder if there is another way for this to happen

**Comment by knizhnik** [comment] 2022-05-20 10:14
GC and compaction are synchronized using the same compaction_cs critical section.
So I do not think that it is some RC between RC and compaction.

Also subsequent error with removing ephemeral files looks suspicious.
Ephemeral files are remove when in-mem layer is destructed. Nobody should try to remove the same inmemory layer and correspondent ephemeral file twice (Arc).

As far as I see - this test run is failed because of timeout expiration. Can this problem be caused by testing framework itself which starts to deleteworking directory while there is still active page server working with this directory?

**Comment by aome510** [comment] 2022-05-20 13:49
I did some runs in https://github.com/neondatabase/neon/pull/1757 to reproduce this error on CI.

So far, the new test failed consistently but now with a different error 😅 .

CI: https://app.circleci.com/pipelines/github/neondatabase/neon/6543/workflows/be3547fa-1d6f-40ac-94b2-0e10c85aeb2a/jobs/66165/artifacts

The new error seems to because of WAL receiver disconnection:

Page server log:
```
2022-05-19T20:59:08.622146Z ERROR WAL receiver{timeline=fa46afd5116e01a9f5980587b1f355db tenant=587c3a9c6266420f9e5538df340c632c}: connection error: connection closed
2022-05-19T20:59:08.622827Z  INFO WAL receiver{timeline=fa46afd5116e01a9f5980587b1f355db tenant=587c3a9c6266420f9e5538df340c632c}: WAL streaming connection failed (connection closed)
```

Safe keeper log:
```
2022-05-19T20:54:57.259516Z ERROR Replication background thread failed: Connection reset by peer (os error 104)
2022-05-19T20:54:58.136127Z ERROR {tid=10}: query handler for 'START_REPLICATION PHYSICAL 0/1696628' failed: failed to run ReplicationConn

Caused by:
    0: Failed to send KeepAlive message
    1: Broken pipe (os error 32)

Stack backtrace:
```

This can probably happen because of CI connection issue on remote machine, so I'll need to run more experiments.

**Comment by aome510** [comment] 2022-05-20 17:08
> I did some runs in https://github.com/neondatabase/neon/pull/1757 to reproduce this error on CI.
> 
> So far, the new test failed consistently but now with a different error 😅 .
> 
> CI: https://app.circleci.com/pipelines/github/neondatabase/neon/6543/workflows/be3547fa-1d6f-40ac-94b2-0e10c85aeb2a/jobs/66165/artifacts
> 
> The new error seems to be because of WAL receiver disconnection:
> ....


Can confirm get this error consistently now. Not sure if it was because I merge the new changes from `main` into #1757 compared to #1735.

**Comment by knizhnik** [comment] 2022-05-20 17:18
> The new error seems to be because of WAL receiver disconnection:

It seems to be not the source of the problem, but result of test termination because of timeout expiration.

**Comment by hlinnaka** [comment] 2022-05-20 17:37
There are several of those safekeeper errors in the log, before the test timeout happens. I think they're caused by abruptly closing the pageserver <-> safekeeper connection, when the pageserver is killed. Can you confirm @arssher or @petuhovskiy? We should probably tone down the logging of those, similar to https://github.com/neondatabase/neon/issues/1683 for the pageserver.

Yeah, the pageserver error is just because the test timed out. We need to increase the timeout on the test to let it finish (I created the test case before the PR that added the timeout was pushed)

**Comment by arssher** [comment] 2022-05-20 18:02
Right, 
```
failed to run ReplicationConn

Caused by:
    0: Failed to send KeepAlive message
    1: Broken pipe (os error 32)
```
just means safekeeper found pageserver <-> safekeeper connection terminated. Yes, we should hide backtrace there.

**Comment by petuhovskiy** [comment] 2022-05-23 09:11
There are a lot of `WARN could not remove ephemeral file ... No such file or directory (os error 2)` on staging, but it's probably a different issue, because they always happen right after detach call. [Link to logs](https://observer.zenith.tech/goto/PZwWX_unk?orgId=1)

**Comment by hlinnaka** [comment] 2022-05-23 09:19
> There are a lot of `WARN could not remove ephemeral file ... No such file or directory (os error 2)` on staging, but it's probably a different issue, because they always happen right after detach call. [Link to logs](https://observer.zenith.tech/goto/PZwWX_unk?orgId=1)

Yeah, seems like a race condition in detach_timeline. I agree it looks like a different bug, there's no DETACH calls in this test. I opened https://github.com/neondatabase/neon/issues/1775 for that.

**Comment by stepashka** [comment] 2022-05-24 16:26
on a discussion today we thought that to confirm thaht this comes from a failed test we may want to revert the test timeout settings, try locally and see if it fails again

**Comment by stepashka** [comment] 2022-05-24 16:27
OTOH, @petuhovskiy mentioned that we had a special, different timeout on circle CI, so may be hard to replicate locally

**Comment by bojanserafimov** [comment] 2022-05-30 18:18
Is there any evidence that CircleCI deletes files? AFAIK it keeps them as artifacts.

**Comment by bojanserafimov** [comment] 2022-05-30 19:00
> Is there any evidence that CircleCI deletes files before killing the whole container?

nevermind, I found that we explicitly add a "Delete all data but logs" step

**Comment by bojanserafimov** [comment] 2022-05-30 21:21
I managed to reproduce this on CI with [this branch](https://github.com/neondatabase/neon/compare/bojan-ci-test?expand=1). Look at the `tmp/test_output/test_timeout[0]/repo/pageserver.log` artifact [here](https://app.circleci.com/pipelines/github/neondatabase/neon/6828/workflows/2ef32d80-81f3-4d00-a5b7-17345b43e851/jobs/69728/artifacts). This concludes that we sometimes delete files while pageserver is still running.

Not sure why some of the `test_timeout` tests passed though. They sleep for more than the CircleCI timeout duration.

**Comment by bojanserafimov** [comment] 2022-08-02 16:33
Let's close it because:
1. We know it's not a pageserver bug, but a CI mistake
2. This CI workflow doesn't exist anymore because we don't use Circle anymore
3. We don't have a "delete all files" step after running tests in our current github workflows

**Closed by bojanserafimov** 2022-08-02 16:33 UTC
Labels: c/storage/pageserver, a/reliability
