### ISSUE TITLE
"could not find layer with more data for key" error in CI 

### ISSUE THREAD

**Issue by lubennikovaav** [neondatabase/neon#1433] opened 2022-03-29 12:07 UTC
`get_reconstruct_data()` doesn't work properly with new storage

on main:
https://app.circleci.com/pipelines/github/zenithdb/zenith/5193/workflows/a91f0101-bc0d-4285-a479-7e8589ca5653/jobs/50233/tests

Error message:
```
asyncpg.exceptions.PostgresIOError: could not read block 159041 in rel 1663/12974/16384.0 from page server at lsn 0/40019F70
E   DETAIL:  page server returned error: could not find layer with more data for key 000000067F000032AE000040000000026D41 at LSN 0/1696628, request LSN 0/40027268, ancestor 0/0
```
pageserver.log:
```
2022-03-29T07:53:53.134358Z ERROR pagestream{timeline=fd2b37b6392d0d030533d477f45842cc tenant=50d5b00c1033457fb6cca08fbe424b3a}:get_page{rel=1663/12974/16384 blkno=159041 req_lsn=0/40019F70}: PATH: result Continue, cont_lsn 0/2001DD59, layer: inmem-000000002001DD59-000000003001F7F9
2022-03-29T07:53:53.134547Z ERROR pagestream{timeline=fd2b37b6392d0d030533d477f45842cc tenant=50d5b00c1033457fb6cca08fbe424b3a}:get_page{rel=1663/12974/16384 blkno=159041 req_lsn=0/40019F70}: PATH: result Continue, cont_lsn 0/1000CFE9, layer: 000000000000000000000000000000000000-FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF__000000001000CFE9-000000002001DD59
2022-03-29T07:53:53.134555Z ERROR pagestream{timeline=fd2b37b6392d0d030533d477f45842cc tenant=50d5b00c1033457fb6cca08fbe424b3a}:get_page{rel=1663/12974/16384 blkno=159041 req_lsn=0/40019F70}: PATH: result Continue, cont_lsn 0/1696629, layer: 000000000000000000000000000000000000-FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF__0000000001696629-000000001000CFE9
2022-03-29T07:53:53.134560Z ERROR pagestream{timeline=fd2b37b6392d0d030533d477f45842cc tenant=50d5b00c1033457fb6cca08fbe424b3a}:get_page{rel=1663/12974/16384 blkno=159041 req_lsn=0/40019F70}: PATH: result Continue, cont_lsn 0/16965B0, layer: 000000000000000000000000000000000000-FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF__00000000016965B0-0000000001696629
2022-03-29T07:53:53.134598Z ERROR pagestream{timeline=fd2b37b6392d0d030533d477f45842cc tenant=50d5b00c1033457fb6cca08fbe424b3a}: error reading relation or page version: could not find layer with more data for key 000000067F000032AE000040000000026D41 at LSN 0/1696628, request LSN 0/40027268, ancestor 0/0
```

Probably the same issue on the branch with unrelated code changes:
https://app.circleci.com/pipelines/github/zenithdb/zenith/5154/workflows/79c37e3a-ef02-4b69-b045-daf4d54106ed/jobs/49885/tests
@arssher, FYI

**Comment by lubennikovaav** [comment] 2022-03-29 12:35
I didn't manage to reproduce it locally.
After some code inspection, I think that the reason for this failure is that the `prev_lsn <= cont_lsn` logic is not correct.

In `get_reconstruct_data()` we check 
- layers.open_layer
- then layers.frozen_layers
- and finally we search for the larest layer in historic_layers.

If layer didn't contain all the data (ValueReconstructResult::Continue), we set cont_lsn = layer.start_lsn.

If `historic_layers` contains a layer, which `start_lsn` (i.e. 0/1696628) is larger than the `start_lsn` of a frozen_layer (i.e. 0/16965B0), prev_lsn check will fail.
IIUC, this can happen if the frozen layer was flushed between `frozen_layers` and  `historic_layers` checks.

@hlinnaka, what do you think?

**Comment by hlinnaka** [comment] 2022-03-29 12:42
> If `historic_layers` contains a layer, which `start_lsn` (i.e. 0/1696628) is larger than the `start_lsn` of a frozen_layer (i.e. 0/16965B0), prev_lsn check will fail. IIUC, this can happen if the frozen layer was flushed between `frozen_layers` and `historic_layers` checks.

Hmm, we hold a the 'layers' lock in `get_reconstruct_data` over the checks in `frozen_layers` and `historic_layers`. So they cannot change within one iteration of the loop. They can change between two iterations, but that seems OK.

**Comment by lubennikovaav** [comment] 2022-03-29 15:42
> Hmm, we hold a the 'layers' lock in `get_reconstruct_data` over the checks in `frozen_layers` and `historic_layers`. So they cannot change within one iteration of the loop. They can change between two iterations, but that seems OK.

I think that layers change between iterations is exactly the problem.
That's how I interpret  what I see in the pageserver.log.
get_reconstruct_data() loop:

1. first iteration
check inmem layer - inmem-000000002001DD59-000000003001F7F9
cont_lsn = start_lsn = 2001DD59

2. few more iterations. inspect frozen layers.
prev_lsn = cont_lsn = 2001DD59
check next layer 000000001000CFE9-000000002001DD59
cont_lsn = start_lsn = 1000CFE9
...
prev_lsn = cont_lsn = 1000CFE9
0000000001696629-000000001000CFE9
cont_lsn = start_lsn = 1696629
....
prev_lsn = cont_lsn = 1696629
00000000016965B0-0000000001696629
cont_lsn = start_lsn = 16965B0

---- concurrently checkpoint frozen layer 0000000001696629. now it is a historic_layer ----

3. next iteration, inspect historic_layer
prev_lsn = cont_lsn = 16965B0
check layer 0000000001696629-???
set cont_lsn = start_lsn = 1696629

4. final iteration 
prev_lsn (16965B0) <= cont_lsn (1696629) ---> ERROR

I don't see any other way to see `cont_lsn` going backward. Do you?

TBH, all this `prev_lsn` check looks like a crutch to hide some real problem. Am I missing something?

**Comment by knizhnik** [comment] 2022-03-31 15:50
I agree with @lubennikovaav - releasing lock between iterations seems to be a source of the problem. Should we kept this lock during iteration within one timeline?

**Comment by lubennikovaav** [comment] 2022-03-31 16:10
@knizhnik , I would rather try to fix the iteration logic. I think this lock will affect performance badly.

**Comment by hlinnaka** [comment] 2022-03-31 18:11
> I don't see any other way to see cont_lsn going backward. Do you?

It shouldn't happen, but clearly there is a bug somewhere...

> TBH, all this prev_lsn check looks like a crutch to hide some real problem. Am I missing something?

It's a sanity check. The loop should make some progress in every iteration; cont_lsn should move backwards in every iteration. The prev_lsn is a way to check that, and break out of the loop if it doesn't make progress for some reason. Otherwise that would lead into an infinite loop.

**Comment by stepashka** [comment] 2022-04-21 10:29
so far @lubennikovaav cannot reproduce this

**Comment by lubennikovaav** [comment] 2022-04-21 12:22
Looks like the upcoming  [pageserver_restart](https://github.com/neondatabase/neon/pull/1324) test bumped into this too.
https://app.circleci.com/pipelines/github/neondatabase/neon/5706/workflows/9aad611c-8b71-4228-85d2-e9d27d9dfa6d/jobs/55600

**Comment by dhammika** [comment] 2022-04-24 22:53
I can repro this in release builds but not on debug builds, even then it's not a page loading error. Is it somehow materializing dup rows? When I load and psql to that timeline,
```
postgres=# \d
          List of relations
 Schema | Name | Type  |    Owner     
--------+------+-------+--------------
 public | foo  | table | zenith_admin
(1 row)

postgres=# select count(x) from foo;
 count  
--------
 158622
(1 row)

postgres=# select count(distinct(x)) from foo;
 count  
--------
 100000
(1 row)

postgres=# select count(*) from (select x, count(x) from foo group by x order by x) as t where count > 1;
 count 
-------
 58622
(1 row)

```

**Comment by knizhnik** [comment] 2022-04-25 08:04
I reproduced the problem with duplicates using my test from #1569 using reduced GC interval.
Looks like this problem is related with GC.

**Comment by stepashka** [comment] 2022-04-25 09:27
@dhammika , i've linked your PR here too
shall we merge it?

**Comment by dhammika** [comment] 2022-04-25 15:28
> I reproduced the problem with duplicates using my test from #1569 using reduced GC interval. Looks like this problem is related with GC.

This is from recovery test in this PR.  #1552 throws a page load error.

**Comment by dhammika** [comment] 2022-04-25 16:23
What's a good way to inspect pages for bad rows?  There's pageinspect extension but I don't think we load it.

**Comment by hlinnaka** [comment] 2022-04-25 16:46
> What's a good way to inspect pages for bad rows? There's pageinspect extension but I don't think we load it.

@antons-antons you added some pageinspect-like functions, didn't you? Can you help out on how to use it?

**Comment by dhammika** [comment] 2022-04-27 16:18
> @dhammika , i've linked your PR here too shall we merge it?

I've merged that but it closed this too (cause of the link?). This is a separate issue though.

**Comment by hlinnaka** [comment] 2022-05-12 12:58
I believe this was the same bug that was fixed by https://github.com/neondatabase/neon/pull/1601. Closing, let's reopen if it happens again.

**Closed by hlinnaka** 2022-05-12 12:58 UTC
Labels: t/bug, c/storage/pageserver
