### ISSUE TITLE
OOMs in staging triggered by `production-like pageserver workload` benchmark

### ISSUE THREAD

**Issue by problame** [neondatabase/neon#6939] opened 2024-02-27 17:24 UTC
# Problem

See channel `#temp-2024-02-26-investigate-ps-ooms`

# Analysis

- PR #6661 made it so we no longer flush in-memory layers after 10min
- That causes us to pile up the InMemoryLayers for all tenants until next restart
- While the values of an InMemoryLayer are page-cached, the `index` is not.
  - As John points out in https://github.com/neondatabase/neon/issues/6916 , these `index`es can actually be large. E.g., 10k tenants with 1 InMemoryLayer each of size 100M can consume `10_000 * 1e6 * 17 / (1024**3) = 158.32` GiB of memory, just for the keys.
- That's the root-cause for the OOM kills.
- After we restart,, we have to re-ingest all the WAL that was piling up in all those InMemoryLayers before the OOM kill.
- That's actually a lot of WAL, at least in the `production-like pageserver workload` benchmark's case.
- This reingestion is what's causing the wait_lsn timeouts
  - See the correlation between [restarts](https://neonprod.grafana.net/explore?schemaVersion=1&panes=%7B%221md%22:%7B%22datasource%22:%22xHHYY0dVz%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bneon_service%3D%5C%22pageserver%5C%22,hostname%3D%5C%22pageserver-2.eu-west-1.aws.neon.build%5C%22%7D%20%7C%3D%20%60git-env:%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22xHHYY0dVz%22%7D,%22editorMode%22:%22code%22%7D%5D,%22range%22:%7B%22from%22:%221708796019000%22,%22to%22:%221708815599000%22%7D%7D%7D&orgId=1) and [wait_lsn timeout errors](https://neonprod.grafana.net/explore?schemaVersion=1&panes=%7B%221md%22:%7B%22datasource%22:%22xHHYY0dVz%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bneon_service%3D%5C%22pageserver%5C%22,hostname%3D%5C%22pageserver-2.eu-west-1.aws.neon.build%5C%22%7D%20%7C~%20%60git-env:%7CTimed%20out%20while%20waiting%20for%20WAL%20record%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22xHHYY0dVz%22%7D,%22editorMode%22:%22code%22%7D%5D,%22range%22:%7B%22from%22:%221708796019072%22,%22to%22:%221708815599000%22%7D%7D%7D&orgId=1)

# Fixing

- Revert #6661 & ship this week's release without it
  - https://github.com/neondatabase/neon/pull/6937
- Cherry-pick revert into `main`
  - https://github.com/neondatabase/neon/pull/6938
- Proper fix
  - https://github.com/neondatabase/neon/pull/6940

# Follow-Ups

```[tasklist]
# Follow-Ups
- [ ] https://github.com/neondatabase/neon/issues/7085
- [ ] global counter metric for received wal bytes, plus warn alert on ab-normal rates/volumes; would have helped highlight that each restart, we were re-ingesting 300GiB of WAL; we only have `pageserver_wal_ingest_records_received`
- [ ] https://github.com/neondatabase/neon/issues/6945
- [ ] gauge for dirty data + alert; this is a good high-level metric that would have made this issue more clear, and it applies to other issues such as clogged upload queue as well
- [ ] eventually: back-pressure on ingest, so that pageserver itself ensures that the gauge never goes above some limit; already have bullet points in #5899 on this issue (i.e. https://github.com/neondatabase/neon/issues/6916)
```

**Comment by problame** [comment] 2024-03-04 11:11
* Vlad has in-progress work, will PR this week.

**Comment by jcsp** [comment] 2024-03-11 11:43
- Intra-batch rolling has been reinstated, so Peter's benchmark no longer directly hits this issue.

**Comment by jcsp** [comment] 2024-03-13 09:31
We've seen the same issue in a different scenario, where the cause of lots of data parallelism was a large number of parallel attaches of tenants with dirty data on the safekeeper, rather than a benchmark.

**Comment by jcsp** [comment] 2024-03-26 15:55
https://github.com/neondatabase/neon/pull/7218 is merged, but disabled by default until we test on staging.

https://github.com/neondatabase/aws/pull/1189 enables the new setting in staging us-east-1.

**Comment by jcsp** [comment] 2024-04-03 17:05
Switching on in next region here https://github.com/neondatabase/aws/pull/1223

**Comment by jcsp** [comment] 2024-04-04 13:30
Prod in a day or two https://github.com/neondatabase/aws/pull/1231

**Comment by jcsp** [comment] 2024-04-05 13:39
Interesting results.  The new mechanism is kicking in (can see "Early-rolling open layer" logs) when the ephemeral data size exceeds the threshold, but the layer rolling isn't preventing the ephemeral byte count from shooting past the limit.

It's possible that this is due to delay in disposing of the layers during flush, but the S3 upload semaphore stats aren't showing a long wait, so this seems unlikely to be totally saturated.  It might be informative to watch this again next week when `pageserver_wal_ingest_bytes_received` is landed in preprod, to get a sense of whether the raw WAL ingest rate could account for  the early-rolling behavior just not keeping up (since it's only enforced every 20 seconds).

Maybe we need https://github.com/neondatabase/neon/issues/7317 to limit ingest while waiting for flushes, but it seems unlikely in this case; there's no evidence that we're bottlenecked on uploads.

**Comment by jcsp** [comment] 2024-04-16 12:24
Unfortunately, the time when we introduced pageserver_wal_ingest_bytes_received is around the same time that the nightly tests were tuned down to be a bit less aggressive, so there's no new information to work with.

**Comment by jcsp** [comment] 2024-04-29 14:11
(9328 tenants is still the default -- maybe staging is still agressive enough to trigger the issue?  But something qualitative changed about how the workload runs)

**Comment by jcsp** [comment] 2024-04-29 17:51
Joonas figured out the likely reason that this wasn't keeping the dirty bytes down in some tests: those tests were overloading compaction, and the call to `maybe_freeze_ephemeral_layer` is happening inside `Timeline::compact` -- a long enough backlog of compaction work stalls the dirty-bytes-driven layer rolling too.

**Comment by jcsp** [comment] 2024-04-29 19:58
Looking at solutions to this...
- We could have a new background task for kicking layer freezing.  I'd rather not have a whole extra task per timeline though.
- We could call tick() on some lsn-driven schedule, e.g. should_roll could check if we have ticked() since the last N bytes of WAL.  However, that would require an extra atomic to store the "last tick" LSN.
- We could make the compaction semaphore waiter run a background task that keeps calling `maybe_freeze_ephemeral_layer` every compaction interval in the background while it waits for the semaphore.

**Comment by jcsp** [comment] 2024-05-02 16:01
Option 1 approach: https://github.com/neondatabase/neon/pull/7594

That plus https://github.com/neondatabase/aws/pull/1231 should close this issue.

**Closed** 2024-05-10 16:08 UTC
Labels: c/storage/pageserver
