### ISSUE TITLE
test_vm_bit_on_clear_lock is flaky

### ISSUE THREAD

**Issue by arpad-m** [neondatabase/neon#7327] opened 2024-04-05 15:20 UTC
51 flaky occurences in the last 14 days:

![Screenshot_20240405_171819](https://github.com/neondatabase/neon/assets/19521842/b124aa42-ce34-47d1-b133-6e840f95e991)

[example](https://neon-github-public-dev.s3.amazonaws.com/reports/pr-7297/8568593494/index.html#testresult/8b77e8e9b323254f/retries):

```
test_runner/regress/test_vm_bits.py:179: in test_vm_bit_clear_on_heap_lock
    assert vm_page_at_pageserver == vm_page_in_cache
E   AssertionError: assert '000000000000...0000000000000' == '000000001800...0000000000000'
E     - 0000000018000020002004200000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
E     ? -----------------------
E     + 0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
E     ?                                                                                                                                                                  +++++++++++++++++++++++
```

**Comment by jcsp** [comment] 2024-04-06 19:37
Dupe of https://github.com/neondatabase/neon/issues/6967 (this ticket has a typo in the test name)

**Closed by jcsp** 2024-04-06 19:37 UTC
Labels: c/storage/pageserver
