### ISSUE TITLE
WAL connection manager should tone down errors while upgrade 

### ISSUE THREAD

**Issue by shanyp** [neondatabase/neon#3337] opened 2023-01-15 11:51 UTC
## Steps to reproduce
Going through the logs of page server during an upgrade

## Expected result
Empty list of ERROR logs

## Actual result
10s of Error messages

## Environment
Prod

## Logs, links
- 2023-01-11T08:40:20.311220Z ERROR wal_connection_manager{tenant=65a9a6336f5b0f70bbf75e70ea82c92b timeline=aecc1d6245f23f0590c0ca1675f22f34}: wal receiver task finished with an error: walreceiver connection handling failure
Caused by:
    0: connection error
    1: db error: ERROR: Failed to process query for timeline aecc1d6245f23f0590c0ca1675f22f34: end streaming to Some("pageserver")
    2: ERROR: Failed to process query for timeline aecc1d6245f23f0590c0ca1675f22f34: end streaming to Some("pageserver")
Stack backtrace:
   0: pageserver::walreceiver::walreceiver_connection::handle_walreceiver_connection::{{closure}}
             at /home/nonroot/pageserver/src/walreceiver/walreceiver_connection.rs:196:38
   1: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/future/mod.rs:91:19
      pageserver::walreceiver::connection_manager::WalreceiverState::change_connection::{{closure}}::{{closure}}::{{closure}}
             at /home/nonroot/pageserver/src/walreceiver/connection_manager.rs:406:18
      <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/future/mod.rs:91:19
   2: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /home/nonroot/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.37/src/instrument.rs:272:9
   3: pageserver::walreceiver::TaskHandle<E>::spawn::{{closure}}
             at /home/nonroot/pageserver/src/walreceiver.rs:118:55
      <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/future/mod.rs:91:19
   4: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /home/nonroot/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.1/src/runtime/task/core.rs:223:17
      tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/nonroot/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.1/src/loom/std/unsafe_cell.rs:14:9
      tokio::runtime::task::core::Core<T,S>::poll
             at /home/nonroot/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.1/src/runtime/task/core.rs:212:13
   5: tokio::runtime::task::harness::poll_future::{{closure}}
             at /home/nonroot/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.1/src/runtime/task/harness.rs:476:19
      <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/panic/unwind_safe.rs:271:9
      std::panicking::try::do_call
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:492:40
      std::panicking::try
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:456:19
      std::panic::catch_unwind
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panic.rs:137:14
      tokio::runtime::task::harness::poll_future
             at /home/nonroot/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.1/src/runtime/task/harness.rs:464:18
      tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /home/nonroot/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.1/src/runtime/task/harness.rs:198:27
      tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/nonroot/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.1/src/runtime/task/harness.rs:152:15
   6: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
   7: tokio::runtime::scheduler::multi_thread::worker::Context::run
   8: tokio::macros::scoped_tls::ScopedKey<T>::set
   9: tokio::runtime::scheduler::multi_thread::worker::run
  10: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
  11: tokio::runtime::task::core::Core<T,S>::poll
  12: tokio::runtime::task::harness::Harness<T,S>::poll
  13: tokio::runtime::blocking::pool::Inner::run
  14: std::sys_common::backtrace::__rust_begin_short_backtrace
  15: core::ops::function::FnOnce::call_once{{vtable.shim}}
  16: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/alloc/src/boxed.rs:1872:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/alloc/src/boxed.rs:1872:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/sys/unix/thread.rs:108:17
  17: start_thread
  18: clone

2023-01-11T08:43:14.174449Z ERROR wal_connection_manager{tenant=7023d89ac7bc138cf602bcfff688ee32 timeline=238047de9342b0d4feef55d7e954e532}: broker subscription failed: status: Unknown, message: "error reading a body from connection: broken pipe", details: [], metadata: MetadataMap { headers: {} }

**Comment by SomeoneToIgnore** [comment] 2023-01-24 12:27
Cannot reproduce.
Here's the recent logs: https://neonprod.grafana.net/explore?orgId=1&left=%7B%22datasource%22%3A%22grafanacloud-logs%22%2C%22queries%22%3A%5B%7B%22refId%22%3A%22A%22%2C%22datasource%22%3A%7B%22type%22%3A%22loki%22%2C%22uid%22%3A%22grafanacloud-logs%22%7D%2C%22editorMode%22%3A%22builder%22%2C%22expr%22%3A%22%7Bunit%3D%5C%22pageserver.service%5C%22%7D+%7C%3D+%60%60%22%2C%22queryType%22%3A%22range%22%7D%5D%2C%22range%22%3A%7B%22from%22%3A%221674563019188%22%2C%22to%22%3A%221674563069288%22%7D%7D

Seems to be no backtraces:

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/2690773/214291377-863a7038-3b80-44e7-b058-d69a745b6b4a.png">

Closing for now, since the code seems to be ok too, it was fixed in https://github.com/neondatabase/neon/pull/3227

**Closed by SomeoneToIgnore** 2023-01-24 12:27 UTC
Labels: t/bug
