### ISSUE TITLE
bmscantest failure in select_parallel pg_regress test

### ISSUE THREAD

**Issue by petuhovskiy** [neondatabase/neon#3928] opened 2023-04-02 08:14 UTC
https://neon-github-public-dev.s3.amazonaws.com/reports/pr-3883/debug/4587612140/index.html#suites/158be07438eb5188d40b466b6acfaeb3/dfdd27c2b7e94c1c/

regression.diffs:
```
diff -U3 /__w/neon/neon/vendor/postgres-v14/src/test/regress/expected/select_parallel.out /tmp/test_output/test_pg_regress/regress/results/select_parallel.out
--- /__w/neon/neon/vendor/postgres-v14/src/test/regress/expected/select_parallel.out	2023-04-02 07:58:00.736609841 +0000
+++ /tmp/test_output/test_pg_regress/regress/results/select_parallel.out	2023-04-02 08:01:21.482620971 +0000
@@ -534,9 +534,9 @@
 insert into bmscantest select r, 'fooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo' FROM generate_series(1,100000) r;
 create index i_bmtest ON bmscantest(a);
 select count(*) from bmscantest where a>1;
- count 
--------
- 99999
+ count  
+--------
+ 100000
 (1 row)
 
 -- test accumulation of stats for parallel nodes
```

**Comment by knizhnik** [comment] 2023-04-02 18:21
Do I correctly understand that the problem reproduced with the latest sources?
It is definitely caused by my parallel bitmap heap scan optimization, but ... I failed to reproduce it locally, even after 100 iterations of test_pg_regress.

**Comment by hlinnaka** [comment] 2024-06-11 19:07
This was fixed in PR https://github.com/neondatabase/neon/pull/3934

**Closed by hlinnaka** 2024-06-11 19:07 UTC
Labels: t/bug, a/test/flaky
