### ISSUE TITLE
`test_subscriber_restart` is flaky

### ISSUE THREAD

**Issue by kelvich** [neondatabase/neon#8097] opened 2024-06-18 15:49 UTC
subj. @knizhnik thinks that timeout is too strict

**Comment by jcsp** [comment] 2024-07-18 08:03
@ololobus did you mean to pause this?  The test is still unstable

**Comment by ololobus** [comment] 2024-07-19 14:37
I marked it as paused because nobody was looking at it after merging an increased timeout. My plan was to look at the list of flaky tests and ask Konstantin to have another look if it's still flaky

**Comment by knizhnik** [comment] 2024-07-19 14:54
I will look. It suffered from the same problem: failed to wait for replica sync. Looks like it is not just timeout problem. But I failed to reproduced it locally.

**Comment by ololobus** [comment] 2024-07-29 13:54
@knizhnik merged a related fix https://github.com/neondatabase/neon/pull/8472. Not sure it will help, but we can observe it for a few days and get back to it

**Comment by ololobus** [comment] 2024-07-29 14:01
Yes, we discussed that with Konstantin. I just wanted to link it because PR was a follow-up to the attempt to reproduce it locally. It fixes an issues with macOS, but in CI we use Linux. The next step could be to create a Linux VM and try to reproduce it there

**Comment by jcsp** [comment] 2024-07-29 16:06
Right, I was trying to fast-forward past the "observe it for a few days" part.

**Comment by ololobus** [comment] 2024-07-30 16:06
This week:

- [ ] Continue investigation
- [ ] Try to reproduce in EC2 if it won't work locally

**Comment by knizhnik** [comment] 2024-07-31 13:33
Failed to reproduce it locally, neither at MacOS, neither at Linux (repeat tests hundred times).
Allure report logs do not provide some useful information: looks like for some reasons connection with published failed to be established.

subscriber:
```
PG:2024-07-30 17:22:42.290 GMT [292395] LOG:  [NEON_SMGR] [shard 0] libpagestore: connected to 'postgresql://no_user@localhost:21282' with protocol version 2
PG:2024-07-30 17:23:18.206 GMT [292388] LOG:  data stream from publisher has ended
PG:2024-07-30 17:23:18.206 GMT [292388] ERROR:  could not send end-of-streaming message to primary: server closed the connection unexpectedly​		This probably means the server terminated abnormally​		before or while processing the request.​	no COPY in progress
```
publisher:
```
PG:2024-07-30 17:22:42.256 GMT [292390] LOG:  [walsender] connection to 127.0.0.1:21285 to fetch WAL succeeded, running START_REPLICATION PHYSICAL 0/1000000 (term='2')
PG:2024-07-30 17:22:42.256 GMT [292390] STATEMENT:  START_REPLICATION SLOT "sub" LOGICAL 0/1959560 (proto_version '2', publication_names '"pub"')
PG:2024-07-30 17:22:42.257 GMT [292390] LOG:  logical decoding found consistent point at 0/174FB58
PG:2024-07-30 17:22:42.257 GMT [292390] DETAIL:  There are no running transactions.
PG:2024-07-30 17:22:42.257 GMT [292390] STATEMENT:  START_REPLICATION SLOT "sub" LOGICAL 0/1959560 (proto_version '2', publication_names '"pub"')
PG:2024-07-30 17:22:43.565 GMT [292390] LOG:  Save replication slot at pg_replslot/sub/state restart_lsn=0/292A6F0
PG:2024-07-30 17:22:43.565 GMT [292390] STATEMENT:  START_REPLICATION SLOT "sub" LOGICAL 0/1959560 (proto_version '2', publication_names '"pub"')
PG:2024-07-30 17:23:03.107 GMT [292390] LOG:  Save replication slot at pg_replslot/sub/state restart_lsn=0/292A6F0
PG:2024-07-30 17:23:03.107 GMT [292390] STATEMENT:  START_REPLICATION SLOT "sub" LOGICAL 0/1959560 (proto_version '2', publication_names '"pub"')
PG:2024-07-30 17:23:03.107 GMT [292390] LOG:  Save replication slot at pg_replslot/sub/state restart_lsn=0/292A9E0
PG:2024-07-30 17:23:03.107 GMT [292390] STATEMENT:  START_REPLICATION SLOT "sub" LOGICAL 0/1959560 (proto_version '2', publication_names '"pub"')
PG:2024-07-30 17:23:17.898 GMT [308063] LOG:  [NEON_SMGR] [shard 0] libpagestore: connected to 'postgresql://no_user@localhost:21282' with protocol version 2
```

**Comment by knizhnik** [comment] 2024-08-03 11:11
I added extra output to this test. And got interesting results. My original assumption was that for some reason replication was stuck.
But looks like it is to true. Please look at flush_lsn of primary before we begin to wait subscriber to caught up.
It is 0/292A7E0. At 5-th iteration subscriber receives WAL up to 0/292A9E0
```
2024-08-03 09:53:36.569 INFO [test_subscriber_restart.py:63] flush_lsn=0/292A7E0
2024-08-03 09:53:36.574 INFO [test_subscriber_restart.py:27] received_lsn=0/1964B10
2024-08-03 09:53:36.585 INFO [test_subscriber_restart.py:30] count=7824
2024-08-03 09:53:36.586 INFO [utils.py:403] waiting for <function test_subscriber_restart.<locals>.check_that_changes_propagated at 0x7f650bf3edc0> iteration 1 failed
2024-08-03 09:53:37.87  INFO [test_subscriber_restart.py:27] received_lsn=0/2328A40
2024-08-03 09:53:37.169 INFO [test_subscriber_restart.py:30] count=62619
2024-08-03 09:53:37.169 INFO [utils.py:403] waiting for <function test_subscriber_restart.<locals>.check_that_changes_propagated at 0x7f650bf3edc0> iteration 2 failed
2024-08-03 09:53:37.670 INFO [test_subscriber_restart.py:27] received_lsn=0/292A8C0
2024-08-03 09:53:37.761 INFO [test_subscriber_restart.py:30] count=96271
2024-08-03 09:53:37.761 INFO [utils.py:403] waiting for <function test_subscriber_restart.<locals>.check_that_changes_propagated at 0x7f650bf3edc0> iteration 3 failed
2024-08-03 09:53:38.262 INFO [test_subscriber_restart.py:27] received_lsn=0/292A9E0
2024-08-03 09:53:38.342 INFO [test_subscriber_restart.py:30] count=96271
2024-08-03 09:53:38.342 INFO [utils.py:403] waiting for <function test_subscriber_restart.<locals>.check_that_changes_propagated at 0x7f650bf3edc0> iteration 4 failed
2024-08-03 09:53:38.843 INFO [test_subscriber_restart.py:27] received_lsn=0/292A9E0
2024-08-03 09:53:38.959 INFO [test_subscriber_restart.py:30] count=96271
2024-08-03 09:53:38.960 INFO [utils.py:403] waiting for <function test_subscriber_restart.<locals>.check_that_changes_propagated at 0x7f650bf3edc0> iteration 5 failed
```
So it receives all WAL after the end of all inserts but still count is smaller than expected - loos like subscriber doesn't receive all records.

**Comment by ololobus** [comment] 2024-08-27 15:44
Looks like it's much more stable after all the fixes -- 99% for the last 7 days, so closing

![Image](https://github.com/user-attachments/assets/23ee09d2-7018-417f-b532-681bbfa17f0f)

**Comment by ololobus** [comment] 2024-09-23 12:31
For some reason, it got much more flaky again and got back to ~90% stability. Let's have another look, reopening
![Image](https://github.com/user-attachments/assets/689c19bf-1aa7-4c31-8a46-374691fb6b8d)

**Comment by knizhnik** [comment] 2024-09-24 08:35
I inspected several recent failures of this test.
Looks like now they are not related with LR itself. All testsI inspected are failed with the following error:
```
RuntimeError: Run ['/tmp/neon/bin/neon_local', 'endpoint', 'start', '--safekeepers', '1', 'ep-2'] failed:
  stdout:
    Starting existing endpoint ep-2...
    Starting postgres node at 'postgresql://cloud_admin@127.0.0.1:15387/postgres'
    SIGKILL & wait the started process
  stderr:
    command failed: timed out waiting to connect to compute_ctl HTTP

    Caused by:
        0: error sending request for url (http://127.0.0.1:15388/status)
        1: client error (Connect)
        2: tcp connect error: Connection refused (os error 111)
        3: Connection refused (os error 111)

    Stack backtrace:
       0: <core::result::Result<T,F> as core::ops::try_trait::FromResidual<core::result::Result<core::convert::Infallible,E>>>::from_residual
                 at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/result.rs:1989:27
          control_plane::endpoint::Endpoint::get_status::{{closure}}
                 at ./control_plane/src/endpoint.rs:718:24
          control_plane::endpoint::Endpoint::start::{{closure}}
                 at ./control_plane/src/endpoint.rs:668:37
```


I wonder if something is changed in compute_ctl or control_plane so that they sometimes failed to connect?
I want to ask help of somebody more familiar with this components.
I even do not know which log should I check to investigate the reasons of the problem.

**Comment by koivunej** [comment] 2024-09-27 12:20
In [report](https://neon-github-public-dev.s3.amazonaws.com/reports/pr-9165/11068081012/index.html#suites/8be0c222d5601535470e7e5978bbfb03/873807e4b5942078) `ep-2` is now panicking:

```
PG:2024-09-27 12:03:48.940 GMT [324262] PANIC:  [WP] collected propEpochStartLsn 0/1835178, but basebackup LSN 0/1835140
PG:2024-09-27 12:03:48.940 GMT [324250] LOG:  background worker "WAL proposer" (PID 324262) was terminated by signal 6: Aborted
```

**Comment by kelvich** [comment] 2024-10-01 15:38
could be related to https://github.com/neondatabase/neon/pull/9099

**Comment by kelvich** [comment] 2024-10-08 15:43
We merged @arssher fix, but it is still flaky. So perhaps few underlying issues.

**Comment by ololobus** [comment] 2024-10-15 16:06
This week:
- [ ] Konstantin: check new failures

**Comment by ololobus** [comment] 2024-11-12 17:08
@knizhnik pls, double-check that recent failures (if any) related to SKs

**Comment by knizhnik** [comment] 2024-11-12 17:22
Actually this test seems to be not lucky any more.
At least it is not mention here in our flaky test triage:
https://neonprod.grafana.net/d/a234c404-1e1a-42b1-bd3b-8e9449cf4563/regression-test-suite-flaky-tests?orgId=1&from=now-7d&to=now&viewPanel=3

**Comment by ololobus** [comment] 2024-11-19 16:33
Indeed, so closing again until we have any new issues

**Closed by ololobus** 2024-11-19 16:33 UTC
Labels: a/test/flaky, c/compute
