### ISSUE TITLE
invalid xlog page header: xlp_magic=0, expected 53520 at LSN

### ISSUE THREAD

**Issue by petuhovskiy** [neondatabase/neon#3319] opened 2023-01-12 17:58 UTC
## Steps to reproduce

Go to safekeeper logs, search for `invalid xlog page header`.

It's unclear what's happening here, but this error appears in all 3 safekeepers and that probably means that compute has an invalid WAL somehow, or it's a bug in the walproposer that sends wrong WAL instead of the right.

We haven't seen this issue affecting any user workload, but it's still worth investigating and fixing.

## Expected result

No such errors in the logs.

## Logs, links

```
2023-01-12T16:59:56.757707Z  INFO {tid=358426}:WAL acceptor{ttid=XXX/YYY}: processed greeting from walproposer C1F1562911FF1CA35944C0BC76FD6968, sending term 1729
2023-01-12T16:59:56.758290Z  INFO {tid=319943}:WAL acceptor{ttid=XXX/YYY}: processed VoteRequest for term 1730: VoteResponse { term: 1730, vote_given: 1, flush_lsn: 0/2EFE000, truncate_lsn: 0/2EFE000, term_history: ... [(1729, 0/2EFE000), (1728, 0/2EF99F8), (1727, 0/2EF99F8), (1726, 0/2EF56F8), (1725, 0/2EF56F8), (1724, 0/2EF03E0), (1723, 0/2EF03E0), (1722, 0/2EEB408), (1721, 0/2EEB408), (1720, 0/2EE6898), (1719, 0/2EE6898), (1718, 0/2EE1FF8), (1717, 0/2EE1FF8), (1716, 0/2EDDBC0), (1715, 0/2EDDBC0), (1714, 0/2ED9A70), (1713, 0/2ED9A70), (1712, 0/2ED5D70), (1711, 0/2ED5D70), (1710, 0/2ED2370)], timeline_start_lsn: 0/149F0F0 }
2023-01-12T16:59:56.758338Z  INFO {tid=330219}:WAL acceptor{ttid=XXX/YYY}: processed VoteRequest for term 1730: VoteResponse { term: 1730, vote_given: 1, flush_lsn: 0/2EFE000, truncate_lsn: 0/2EFE000, term_history: ... [(1729, 0/2EFE000), (1728, 0/2EF99F8), (1727, 0/2EF99F8), (1726, 0/2EF56F8), (1725, 0/2EF56F8), (1724, 0/2EF03E0), (1723, 0/2EF03E0), (1722, 0/2EEB408), (1721, 0/2EEB408), (1720, 0/2EE6898), (1719, 0/2EE6898), (1718, 0/2EE1FF8), (1717, 0/2EE1FF8), (1716, 0/2EDDBC0), (1715, 0/2EDDBC0), (1714, 0/2ED9A70), (1713, 0/2ED9A70), (1712, 0/2ED5D70), (1711, 0/2ED5D70), (1710, 0/2ED2370)], timeline_start_lsn: 0/149F0F0 }
2023-01-12T16:59:56.758633Z  INFO {tid=358426}:WAL acceptor{ttid=XXX/YYY}: processed VoteRequest for term 1730: VoteResponse { term: 1730, vote_given: 1, flush_lsn: 0/2EFE000, truncate_lsn: 0/2EFE000, term_history: ... [(1729, 0/2EFE000), (1728, 0/2EF99F8), (1727, 0/2EF99F8), (1726, 0/2EF56F8), (1725, 0/2EF56F8), (1724, 0/2EF03E0), (1723, 0/2EF03E0), (1722, 0/2EEB408), (1721, 0/2EEB408), (1720, 0/2EE6898), (1719, 0/2EE6898), (1718, 0/2EE1FF8), (1717, 0/2EE1FF8), (1716, 0/2EDDBC0), (1715, 0/2EDDBC0), (1714, 0/2ED9A70), (1713, 0/2ED9A70), (1712, 0/2ED5D70), (1711, 0/2ED5D70), (1710, 0/2ED2370)], timeline_start_lsn: 0/149F0F0 }
2023-01-12T16:59:56.758908Z  INFO {tid=319943}:WAL acceptor{ttid=XXX/YYY}: received ProposerElected ProposerElected { term: 1730, start_streaming_at: 0/2EFE000, term_history: ... [(1730, 0/2EFE000), (1729, 0/2EFE000), (1728, 0/2EF99F8), (1727, 0/2EF99F8), (1726, 0/2EF56F8), (1725, 0/2EF56F8), (1724, 0/2EF03E0), (1723, 0/2EF03E0), (1722, 0/2EEB408), (1721, 0/2EEB408), (1720, 0/2EE6898), (1719, 0/2EE6898), (1718, 0/2EE1FF8), (1717, 0/2EE1FF8), (1716, 0/2EDDBC0), (1715, 0/2EDDBC0), (1714, 0/2ED9A70), (1713, 0/2ED9A70), (1712, 0/2ED5D70), (1711, 0/2ED5D70)], timeline_start_lsn: 0/149F0F0 }
2023-01-12T16:59:56.758949Z  INFO {tid=330219}:WAL acceptor{ttid=XXX/YYY}: received ProposerElected ProposerElected { term: 1730, start_streaming_at: 0/2EFE000, term_history: ... [(1730, 0/2EFE000), (1729, 0/2EFE000), (1728, 0/2EF99F8), (1727, 0/2EF99F8), (1726, 0/2EF56F8), (1725, 0/2EF56F8), (1724, 0/2EF03E0), (1723, 0/2EF03E0), (1722, 0/2EEB408), (1721, 0/2EEB408), (1720, 0/2EE6898), (1719, 0/2EE6898), (1718, 0/2EE1FF8), (1717, 0/2EE1FF8), (1716, 0/2EDDBC0), (1715, 0/2EDDBC0), (1714, 0/2ED9A70), (1713, 0/2ED9A70), (1712, 0/2ED5D70), (1711, 0/2ED5D70)], timeline_start_lsn: 0/149F0F0 }
2023-01-12T16:59:56.759146Z  INFO {tid=358426}:WAL acceptor{ttid=XXX/YYY}: received ProposerElected ProposerElected { term: 1730, start_streaming_at: 0/2EFE000, term_history: ... [(1730, 0/2EFE000), (1729, 0/2EFE000), (1728, 0/2EF99F8), (1727, 0/2EF99F8), (1726, 0/2EF56F8), (1725, 0/2EF56F8), (1724, 0/2EF03E0), (1723, 0/2EF03E0), (1722, 0/2EEB408), (1721, 0/2EEB408), (1720, 0/2EE6898), (1719, 0/2EE6898), (1718, 0/2EE1FF8), (1717, 0/2EE1FF8), (1716, 0/2EDDBC0), (1715, 0/2EDDBC0), (1714, 0/2ED9A70), (1713, 0/2ED9A70), (1712, 0/2ED5D70), (1711, 0/2ED5D70)], timeline_start_lsn: 0/149F0F0 }
2023-01-12T16:59:56.760996Z  INFO {tid=330219}:WAL acceptor{ttid=XXX/YYY}: start receiving WAL since 0/2EFE000
2023-01-12T16:59:56.761114Z  INFO {tid=358426}:WAL acceptor{ttid=XXX/YYY}: start receiving WAL since 0/2EFE000
2023-01-12T16:59:56.761138Z  INFO {tid=319943}:WAL acceptor{ttid=XXX/YYY}: start receiving WAL since 0/2EFE000
2023-01-12T16:59:56.761145Z  INFO stopping WAL backup task for XXX/YYY
2023-01-12T16:59:56.761214Z  INFO stopping WAL backup task for XXX/YYY
2023-01-12T16:59:56.761253Z  INFO stopping WAL backup task for XXX/YYY
2023-01-12T16:59:56.761190Z  INFO WAL backup task{ttid=XXX/YYY}: task canceled
2023-01-12T16:59:56.761204Z ERROR {tid=358426}: query handler for 'START_WAL_PUSH' failed: Failed to process query for timeline XXX/YYY
Caused by:
    invalid xlog page header: xlp_magic=0, expected 53520 at 0/2EFE000
```

## Notes

Would be useful to add some sort of tracing to have unique compute id in the safekeeper logs. After that we can add tools to quickly jump to according compute logs for any safekeeper connection.

**Comment by kelvich** [comment] 2023-01-13 08:57
Let's also tag all safekeeper logs. Storage manager puts '[SMGR]' in front of all log lines https://github.com/neondatabase/neon/blob/main/pgxn/neon/pagestore_client.h#L52-L55 and it is handy to filter

**Comment by kelvich** [comment] 2023-01-13 08:58
> unique compute id in the safekeeper logs
endpoint name? or want this thing to be changed each time compute starts to narrow scope?

**Comment by petuhovskiy** [comment] 2023-01-13 12:38
> Let's also tag all safekeeper logs. Storage manager puts '[SMGR]' in front of all log lines ...

I looked at the compute logs and it seems that we already log process PID:
```
2023-01-13 11:39:04.779 GMT [21] LOG:  connecting with node zenith-1-sk-4.local:6500

[21] is walproposer's PID in this case
```

This PID is enough to filter walproposer-only logs, so I'm not sure if it's worth appending another tag to walproposer logs.

**Comment by arssher** [comment] 2023-02-07 04:16
> Would be useful to add some sort of tracing to have unique compute id in the safekeeper logs.
+1, we already have unique walproposer_id transferred in the protocol, it is easy to log it. Perhaps better to shorted it though...

But I'd still add `[WP]` prefix to walproposer.c logging or something. Currently compute logs don't contain much except walproposer logs, but this might not stay so.

**Comment by arssher** [comment] 2023-02-07 04:28
So, initial explanation:
-  this happens only when backup_lsn happens to be at the page boundary
-  if it happens, all safekeepers complain on that (hinting that indeed sent data is wrong), sent data is always 0
-  after the error connections are reset, but on next attempt error disappears.

Note that when backup_lsn is on page boundary, it always points to the beginning of the next record, not to the page header -- pageserver issues it this way, most likely because StartupXLOG wishes it to be so. Thus we initialize the page header on compute during the start. And it seems like walproposer might start sending WAL earlier than this initialization finished, but not sure yet.

**Comment by arssher** [comment] 2023-02-23 14:13
@petuhovskiy let's try to write WAL up to 8KB page boundary and restart compute. If that's not enough (not reproduces), can try to add sleep into startup process doing recovery (while walproposer is already active, supposedly).

**Closed** 2023-07-19 09:48 UTC
Labels: t/bug, c/storage/safekeeper
