### ISSUE TITLE
Large wal_acceptor_reconnect_timeout impacts performance

### ISSUE THREAD

**Issue by arssher** [neondatabase/neon#4534] opened 2023-06-19 11:47 UTC
https://neondb.slack.com/archives/C04BLQ4LW7K/p1686736854174559

**Comment by petuhovskiy** [comment] 2023-06-19 12:07
Dupe of #4517

**Closed by petuhovskiy** 2023-06-19 12:07 UTC
Labels: c/storage/safekeeper

**Comment by arssher** [comment] 2023-06-19 12:09
Added safekeepers label so I'm not miss it again.
