### ISSUE TITLE
 CREATE TABLE t(key int primary key, value text) ERROR:  could not read block 4 in rel 1663/5/2704.0 from page server at lsn 0/014B0710

### ISSUE THREAD

**Issue by william-lbn** [neondatabase/neon#6319] opened 2024-01-11 01:34 UTC
## Steps to reproduce
I followed the steps of docker.md(https://github.com/neondatabase/neon/blob/main/docs/docker.md)

## Expected result
Run the software normally and create database tables

## Actual result

```
(base)@MacBook-Pro docker-compose % psql -h 127.0.0.1 -p 55433 -U cloud_admin postgres
Password for user cloud_admin: 
psql (16.1, server 15.2)
Type "help" for help.

postgres=# CREATE TABLE t(key int primary key, value text);
ERROR:  could not read block 4 in rel 1663/5/2704.0 from page server at lsn 0/014B0710
LINE 1: CREATE TABLE t(key int primary key, value text);
DETAIL:  page server returned error: Failed to reconstruct a page image:
```

## Environment
MacBook-Pro(M1)  Docker Desktop 4.20.1 (110738) is currently the newest version available.

![image](https://github.com/neondatabase/neon/assets/10280419/2aaddede-923e-4a47-b2fa-0282d9742e42)

## Logs, links
- 

![image](https://github.com/neondatabase/neon/assets/10280419/a8b84e6b-6ab7-40ee-b15d-3ab68fafbdf4)

```
(base)@MacBook-Pro docker-compose % psql -h 127.0.0.1 -p 55433 -U cloud_admin postgres
Password for user cloud_admin: 
psql (16.1, server 15.2)
Type "help" for help.

postgres=# CREATE TABLE t(key int primary key, value text);
ERROR:  could not read block 4 in rel 1663/5/2704.0 from page server at lsn 0/014B0710
LINE 1: CREATE TABLE t(key int primary key, value text);
                           ^
DETAIL:  page server returned error: Failed to reconstruct a page image:
```

![image](https://github.com/neondatabase/neon/assets/10280419/776b3d63-de30-49a5-82d6-9f2f5e370177)

**Comment by william-lbn** [comment] 2024-01-11 01:37
minio  

![image](https://github.com/neondatabase/neon/assets/10280419/ad308a73-4958-4295-9e34-28605a783ef3)

**Comment by hlinnaka** [comment] 2024-06-11 20:31
I don't know what the problem was, but it works for me :shrug: . I'm closing this, but please re-open if you can still reproduce it.

(Right now, there's another problem with the docker-compose file, see https://github.com/neondatabase/neon/pull/7818#issuecomment-2161482419, but you can just comment out the `eondatabase/neon-test-extensions-v16` image from the docker-compose.yml file to work around that)

**Closed by hlinnaka** 2024-06-11 20:31 UTC
Labels: t/bug
