### ISSUE TITLE
`could not remove ephemeral file` WARN-level log messages

### ISSUE THREAD

**Issue by problame** [neondatabase/neon#3372] opened 2023-01-18 11:24 UTC
Observe production logs: https://neonprod.grafana.net/goto/dHZimno4k?orgId=1

We frequently get messages like this one:

```
2023-01-18T11:19:25.064038Z  WARN tenant_detach{tenant=76c07b269ea5a86ee7e5e2a4e33c0a7e}: could not remove ephemeral file '/storage/pageserver/data/tenants/76c07b269ea5a86ee7e5e2a4e33c0a7e/timelines/955f158e367974476cb32bb2a7d01546/ephemeral-1513': No such file or directory (os error 2)
```

Sampling some of those tenant UUIDs, it appears that they are short-lived projects created & destroyed by the e2e-tests.

Tasks:

- [ ] Root cause & fix the failure. Or, identify the case and don't log WARN in this case.

**Comment by hlinnaka** [comment] 2023-01-18 11:45
Duplicate of https://github.com/neondatabase/neon/issues/3060, I believe

**Comment by shanyp** [comment] 2023-01-31 15:25
closing as dup

**Closed by shanyp** 2023-01-31 15:25 UTC
Labels: t/bug, c/storage/pageserver, a/observability
