### ISSUE TITLE
race in set_tenant_state

### ISSUE THREAD

**Issue by bojanserafimov** [neondatabase/neon#2003] opened 2022-06-27 22:28 UTC
1. Thread 1 sets state to idle and drops mutex
2. Thread 2 sets state to active and starts gc/compaction threads
3. Thread 1 kills the threads
4. Now we have an active tenant with no threads

cc @SomeoneToIgnore

**Comment by shanyp** [comment] 2023-03-14 11:45
closing this one as duplicate of #2727

**Closed by shanyp** 2023-03-14 11:45 UTC
Labels: t/bug, c/storage/pageserver, c/storage
