### ISSUE TITLE
Failures in `test_restart_endpoint_after_switch_wal`

### ISSUE THREAD

**Issue by jcsp** [neondatabase/neon#9259] opened 2024-10-03 08:58 UTC
This test is failing ~1.5% of the time.

It was added in https://github.com/neondatabase/neon/pull/8943

Examples:

## Case 1

https://neon-github-public-dev.s3.amazonaws.com/reports/pr-6560/11150102484/index.html#testresult/32593da5b1e125d1/retries

```
RuntimeError: Run ['/tmp/neon/bin/neon_local', 'endpoint', 'start', '--safekeepers', '1', 'ep-2'] failed:
  stdout:
    Starting existing endpoint ep-2...
    Starting postgres node at 'postgresql://cloud_admin@127.0.0.1:31674/postgres'
    SIGKILL & wait the started process
  stderr:
    command failed: timed out waiting to connect to compute_ctl HTTP

    Caused by:
        0: error sending request for url (http://127.0.0.1:31675/status)
        1: client error (Connect)
        2: tcp connect error: Connection refused (os error 111)
        3: Connection refused (os error 111)
```

## Case 2

https://neon-github-public-dev.s3.amazonaws.com/reports/pr-9232/11153678585/index.html#/testresult/ace582de47d6f7a9

```
test_runner/regress/test_wal_acceptor.py:1076: in test_restart_endpoint_after_switch_wal
    endpoint.safe_psql("SELECT 'works'")
test_runner/fixtures/neon_fixtures.py:330: in safe_psql
    return self.safe_psql_many([query], **kwargs)[0]
test_runner/fixtures/neon_fixtures.py:340: in safe_psql_many
    with closing(self.connect(**kwargs)) as conn:
test_runner/fixtures/neon_fixtures.py:284: in connect
    conn: PgConnection = psycopg2.connect(**self.conn_options(**kwargs))
/github/home/.cache/pypoetry/virtualenvs/non-package-mode-_pxWMzVK-py3.9/lib/python3.9/site-packages/psycopg2/__init__.py:122: in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
E   psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 28828 failed: server closed the connection unexpectedly
E   	This probably means the server terminated abnormally
E   	before or while processing the request.
```

**Comment by erikgrinaker** [comment] 2024-10-04 11:22
The compute fails to restart due to a panic in the WAL proposer (from `ep-2/compute.log`):

* [Case 1](https://neon-github-public-dev.s3.amazonaws.com/reports/pr-6560/11150102484/index.html#testresult/98140000c97855a8/)

    ```
    PG:2024-10-02 19:33:38.546 GMT [392338] PANIC:  [WP] collected propEpochStartLsn 0/2000000, but basebackup LSN 0/152CBC8
    ```

* [Case 2](https://neon-github-public-dev.s3.amazonaws.com/reports/pr-9232/11153678585/index.html#/testresult/ace582de47d6f7a9) 

    ```
    PG:2024-10-03 01:01:17.098 GMT [332945] PANIC:  [WP] collected propEpochStartLsn 0/2002078, but basebackup LSN 0/15206D8
    ```

I'm not familiar with the background here, perhaps @arssher can shed some light on it.

**Comment by arssher** [comment] 2024-10-04 13:54
https://github.com/neondatabase/neon/pull/9099 (merged 01.10 17:54 UTC) was supposed to fix this. I haven't exactly verified whether this PR is included in the runs above (with force pushes it's probably impossible), but let's see if failures repeat on fresh PRs.

**Comment by erikgrinaker** [comment] 2024-10-04 13:56
Random notes from poking around:

* The `propEpochStartLsn` is [taken from the safekeeper's `flushLsn`](https://github.com/neondatabase/neon/blob/09d4bad1be6ed229d2537b43040a8de4ea0e865b/pgxn/neon/walproposer.c#L944) (the last durable LSN).
* The basebackup LSN during recovery is [taken from the control file](https://github.com/neondatabase/postgres/blob/16c3c6b64f1420a367a2a9b2510f20d94f791af8/src/backend/access/transam/xlogrecovery.c#L786-L801), which we generate.
* The `pageserver` [constructs and sends the basebackup](https://github.com/neondatabase/neon/blob/42ef08db470e24853fe4c77acb5fd84a1bcb2356/pageserver/src/page_service.rs#L1151-L1158) in response to an RPC call. The caller provides the LSN.
* In case 1, the caller did provide an explicit `0/152CBC8` LSN for the base backup.
* The [basebackup is adjusted for the last record](https://github.com/neondatabase/neon/blob/78938d1b591b33d23495a0edb8b123cc5cac6a27/pageserver/src/basebackup.rs#L67-L98), but the WAL switch may not have added a new record.

Heading into a meeting, will pick this back up on Monday.

**Comment by erikgrinaker** [comment] 2024-10-04 13:57
Thanks @arssher, #9099 makes sense. Let's look for any newer failures.

**Comment by erikgrinaker** [comment] 2024-10-04 14:54
I checked all the failures on `main`, none of them were because of this problem, but rather errors on test cleanup and such (e.g. `postmaster.pid` missing on `stop`). I'll have a closer look at them next week.

**Comment by erikgrinaker** [comment] 2024-10-14 10:51
I think I know what the problem is. If the walreceiver is closed while processing a WAL append (using `NoFlushAppendRequest`) then we may break out of the `WalAcceptor` loop before the WAL record is flushed to disk.

https://github.com/neondatabase/neon/blob/cbcd4058edb7a2c2bb3bfe1a6fc1ffb0d820b870/safekeeper/src/receive_wal.rs#L520-L539

When `--sync-safekeepers` comes around to query the safekeeper's `propEpochStartLsn` it sends a `TIMELINE_STATUS` query. The last record will not be reflected in `flush_lsn`, since it hasn't been flushed yet.

https://github.com/neondatabase/neon/blob/97582178cb576f8b68acc53535adf8918d7dbd94/safekeeper/src/handler.rs#L285-L311

However, when the compute then starts up and sends a `VoteRequest` to the safekeeper, the safekeeper will flush the timeline to disk before processing the vote:

https://github.com/neondatabase/neon/blob/e287f36a058221b7c804b4b0f440933962eb3deb/safekeeper/src/safekeeper.rs#L644-L659

This will cause the previous unflushed WAL record to be flushed to disk and advance the `flush_lsn`, causing the `VoteResponse` to have a `propEpochStartLsn` after the basebackup LSN from `--sync-safekeepers`.

@arssher Does the above check out? A simple fix might be to ensure the walreceiver flushes any appended records on disconnect. Let me know if that sounds good and I'll submit a PR.

**Comment by arssher** [comment] 2024-10-16 16:22
> Does the above check out?

Yes, it makes sense.

> A simple fix might be to ensure the walreceiver flushes any appended records on disconnect

It should work indeed, but as an alternative I think it would be ok to disable this 'skip sync-safekeepers' optimization altogether, I suspect that it doesn't give us much. If needed we can enable it back later in a better shape -- http instead of pg protocol and force bump term.

**Comment by erikgrinaker** [comment] 2024-10-17 08:26
> as an alternative I think it would be ok to just disable this 'skip sync-safekeepers' optimization altogether, I suspect that it doesn't give us much

The [original PR](https://github.com/neondatabase/neon/pull/4804) seems to indicate that spinning up a Postgres process just for `--sync-safekeepers` is expensive enough to matter for cold start times. I imagine we hit this fast path quite often for mostly-idle projects. 

Let me prepare PRs for both approaches, and we can discuss them there; they're both pretty trivial.

**Comment by erikgrinaker** [comment] 2024-10-17 12:23
PRs:

* #9436
* #9429

I think we should do #9436 regardless, and then optionally #9429 if we think it makes sense on its own merit.

**Comment by erikgrinaker** [comment] 2024-10-17 15:24
I expect #9436 will fix this, but I'll keep this open as a reminder to check that we haven't seen further flakes in a few days.

**Comment by erikgrinaker** [comment] 2024-10-27 20:13
No failures since merging #9436, closing.

**Closed by erikgrinaker** 2024-10-27 20:13 UTC
Labels: t/bug, c/storage/safekeeper, a/test
