### ISSUE TITLE
PG: `neon_superuser` is unable to `GRANT USAGE` on sequences created by extensions

### ISSUE THREAD

**Issue by brendan-stephens** [neondatabase/neon#6236] opened 2023-12-27 16:12 UTC
## Steps to reproduce

```
zeustra_ssot=> CREATE EXTENSION address_standardizer_data_us ;
CREATE EXTENSION

zeustra_ssot=> create role sf_sync with password 'q2w3E$R%t6Y&' login;
CREATE ROLE

zeustra_ssot=> grant sf_sync to brendan;
GRANT ROLE
zeustra_ssot=> set role sf_sync;
SET

zeustra_ssot=> select count(*) from us_gaz;
```

## Expected result

```
zeustra_ssot=> select count(*) from us_gaz;
 count
-------
  1074
(1 row)
```

## Actual result
```
zeustra_ssot=> select count(*) from us_gaz;
ERROR:  permission denied for table us_gaz
```

When `cloud_admin` creates the extension, sequences can be created:

```
zeustra_ssot=> \d us_gaz;
                              Table "public.us_gaz"
  Column   |  Type   | Collation | Nullable |              Default
-----------+---------+-----------+----------+------------------------------------
 id        | integer |           | not null | nextval('us_gaz_id_seq'::regclass)
 seq       | integer |           |          |
 word      | text    |           |          |
 stdword   | text    |           |          |
 token     | integer |           |          |
 is_custom | boolean |           | not null | true
Indexes:
    "pk_us_gaz" PRIMARY KEY, btree (id)
    
zeustra_ssot=> SELECT rolname, has_sequence_privilege(rolname, 'us_gaz_id_seq', 'usage, select, update') from pg_roles where rolname not like 'pg_%';
    rolname     | has_sequence_privilege
----------------+------------------------
 cloud_admin    | t
 neon_superuser | t
 brendan        | t
 sf_sync        | f

zeustra_ssot=> set role neon_superuser ;
SET
zeustra_ssot=> GRANT USAGE, SELECT ON SEQUENCE us_gaz_id_seq to sf_sync ;
WARNING:  no privileges were granted for "us_gaz_id_seq"
GRANT
```

This renders users unable to grant usage to the sequences, unless the users are created at the console.

**Comment by skyzh** [comment] 2024-02-12 18:16
a minimal reproduction:

```
CREATE EXTENSION address_standardizer_data_us;
SELECT rolname, has_sequence_privilege(rolname, 'us_gaz_id_seq', 'usage, select, update') from pg_roles where rolname not like 'pg_%';
grant usage, select on sequence us_gaz_id_seq to new_role;
```

it also does not work with table, not just sequence, so i guess the hooks in the neon extensions are not working correctly. looking into that...

**Comment by skyzh** [comment] 2024-02-12 18:40
by looking at `select * from information_schema.table_privileges;`, tables created by extensions did not appear in this information schema table, which indicates something wrong with our create table process that did not correctly set up the privileges initially?

**Comment by skyzh** [comment] 2024-02-12 20:17
adding `superuser = false` to the extension control file can mitigate the issue, and i'm looking into the root cause right now

**Comment by hlinnaka** [comment] 2024-02-16 19:42
Back to the drawing board for the proper fix:

The reason that the  address_standardizer_data_us extension is owned by the bootstrap superuser, instead of the user that runs the CREATE EXTENSION command, is that it's marked as 'trusted=true' in the control file. But why is it marked as 'trusted=true'? AFAICS the installation script doesn't actually perform any operations that would require superuser privilege. Instead of marking it as 'trusted=true', we can mark it as 'superuser= false', to allow any user to install it.

**Comment by skyzh** [comment] 2024-02-16 19:44
> Instead of marking it as 'trusted=true', we can mark it as 'superuser= false', to allow any user to install it.

Yes sounds true. But I think for now we just appended `trusted = true` to all extensions we install on the compute node. `address_standardizer_data_us` is one of them.

https://github.com/neondatabase/neon/blob/5d039c6e9b0662bb81407819540162a06334791c/Dockerfile.compute-node#L41-L51

**Comment by skyzh** [comment] 2024-02-16 19:45
https://github.com/neondatabase/neon/blob/5d039c6e9b0662bb81407819540162a06334791c/Dockerfile.compute-node#L109-L115

**Comment by skyzh** [comment] 2024-02-20 16:40
reverted due to not working with pgvector.

may be fixed by grant default permissions to neon_superuser, testing and hopefully we can fix this issue soon.

**Comment by vadim2404** [comment] 2024-02-20 16:53
@skyzh to sync with @andreasscherbaum

**Closed** 2024-02-21 21:09 UTC
Labels: t/bug, c/storage/compute

**Comment by skyzh** [comment] 2024-02-22 21:35
Current restrictions (and the solutions) -- https://neondb.slack.com/archives/C04DGM6SMTM/p1708637692434039
