### ISSUE TITLE
test_pageserver_chaos is flacky

### ISSUE THREAD

**Issue by SomeoneToIgnore** [neondatabase/neon#2806] opened 2022-11-14 14:10 UTC
Had noticed it failing a few times on a `release` configuration:

https://neon-github-public-dev.s3.amazonaws.com/reports/main/release/3461576088/index.html#suites/094ca0c3798926b0b3676f7b1a8a5bdb/2295ffad082a2001/

```
2022-11-14 13:10:26.197 INFO [neon_fixtures.py:1319] Running command "/tmp/neon/bin/neon_local pageserver start"
2022-11-14 13:10:26.197 INFO [neon_fixtures.py:1320] Running in "/tmp/test_output/test_pageserver_chaos/repo"
2022-11-14 13:10:26.703 INFO [neon_fixtures.py:1347] Run success: Starting pageserver at 'localhost:18092' in '/tmp/test_output/test_pageserver_chaos/repo'
.
pageserver started, pid: 21041
2022-11-14 13:10:27.978 INFO [neon_fixtures.py:779] Cleaning up all storage and compute nodes
2022-11-14 13:10:27.978 INFO [neon_fixtures.py:1319] Running command "/tmp/neon/bin/neon_local pg stop --tenant-id 7632caa8864f134a8cd42793a7f3eeee test_pageserver_chaos_pg_node"
2022-11-14 13:10:27.978 INFO [neon_fixtures.py:1320] Running in "/tmp/test_output/test_pageserver_chaos/repo"
2022-11-14 13:10:28.29  INFO [neon_fixtures.py:1355]             Run ['/tmp/neon/bin/neon_local', 'pg', 'stop', '--tenant-id', '7632caa8864f134a8cd42793a7f3eeee', 'test_pageserver_chaos_pg_node'] failed:
              stdout: 
              stderr: command failed: pg_ctl failed, exit code: exit status: 1, stdout: , stderr: pg_ctl: PID file "/tmp/test_output/test_pageserver_chaos/repo/pgdatadirs/tenants/7632caa8864f134a8cd42793a7f3eeee/test_pageserver_chaos_pg_node/postmaster.pid" does not exist
Is server running?


Stack backtrace:
   0: control_plane::compute::PostgresNode::pg_ctl
             at ./control_plane/src/compute.rs:453:13
   1: neon_local::handle_pg
             at ./control_plane/src/bin/neon_local.rs:688:13
   2: neon_local::main
             at ./control_plane/src/bin/neon_local.rs:109:21
   3: core::ops::function::FnOnce::call_once
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/ops/function.rs:248:5
      std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/sys_common/backtrace.rs:122:18
   4: std::rt::lang_start::{{closure}}
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/rt.rs:145:18
   5: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/ops/function.rs:280:13
      std::panicking::try::do_call
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:492:40
      std::panicking::try
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:456:19
      std::panic::catch_unwind
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panic.rs:137:14
      std::rt::lang_start_internal::{{closure}}
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/rt.rs:128:48
      std::panicking::try::do_call
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:492:40
      std::panicking::try
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:456:19
      std::panic::catch_unwind
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panic.rs:137:14
      std::rt::lang_start_internal
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/rt.rs:128:20
   6: main
   7: __libc_start_main
   8: _start
```

Seems that we're too fast to check for the process to start, but needs more investigation.

**Comment by hlinnaka** [comment] 2022-11-14 14:22
The real culprit is this, in `pg.log`:
```
2022-11-14 13:10:24.286 GMT [17288] LOG:  [NEON_SMGR] dropping connection to page server due to error
2022-11-14 13:10:24.286 GMT [17288] ERROR:  [NEON_SMGR] could not get response from pageserver: server closed the connection unexpectedly
		This probably means the server terminated abnormally
		before or while processing the request.
	
2022-11-14 13:10:25.287 GMT [17288] ERROR:  [NEON_SMGR] could not establish connection to pageserver
2022-11-14 13:10:25.287 GMT [17288] DETAIL:  connection to server at "localhost" (127.0.0.1), port 18092 failed: Connection refused
		Is the server running on that host and accepting TCP/IP connections?
	connection to server at "localhost" (::1), port 18092 failed: Cannot assign requested address
		Is the server running on that host and accepting TCP/IP connections?
2022-11-14 13:10:26.288 GMT [17288] WARNING:  [NEON_SMGR] Tried to flush while disconnected
2022-11-14 13:10:26.705 GMT [21076] LOG:  [NEON_SMGR] libpagestore: connected to 'postgresql://no_user:@localhost:18092'
2022-11-14 13:10:27.043 GMT [17283] LOG:  autovacuum launcher process (PID 17288) was terminated by signal 11: Segmentation fault
2022-11-14 13:10:27.043 GMT [17283] LOG:  terminating any other active server processes
2022-11-14 13:10:27.044 GMT [17283] LOG:  shutting down because restart_after_crash is off
2022-11-14 13:10:27.045 GMT [17283] LOG:  database system is shut down
```
Postgres segfaulted (I'm guessing because of https://github.com/neondatabase/neon/issues/2780, but doesn't matter really why), and because of that, `neon_local pg stop` returns an error, as the process wasn't running as it expected.

**Comment by koivunej** [comment] 2022-11-16 09:37
#2790 was merged and I think this is only a duplicate of the #2780 as mentioned, closing.

**Closed by koivunej** 2022-11-16 09:37 UTC
Labels: c/storage
