### ISSUE TITLE
cannot complete vacuum full because size limit is reached

### ISSUE THREAD

**Issue by LizardWizzard** [neondatabase/neon#1445] opened 2022-03-31 15:08 UTC
@lubennikovaav AFAIK, we planned to allow vacuum operations even when size limit is reached, so I'm not sure if this already should work or it is in the TODO list
```
VACUUM FULL
Reconnecting...
Reconnected!
could not extend file because cluster size limit (10000 MB) has been exceeded
HINT:  This limit is defined by zenith.max_cluster_size GUC
```

**Comment by arssher** [comment] 2022-12-21 06:47
dupe of https://github.com/neondatabase/neon/issues/1245

**Closed by arssher** 2022-12-21 06:47 UTC
Labels: t/bug, c/storage/pageserver, c/cloud/compute
