### ISSUE TITLE
initdb_lsn is not reproducible

### ISSUE THREAD

**Issue by SomeoneToIgnore** [neondatabase/neon#2592] opened 2022-10-09 11:04 UTC
Pageserver, in order to create an empty timeline, runs `initdb` command: https://github.com/neondatabase/neon/blob/3be3bb77302c371d1c58fda7d17dbf56dd9ad061/pageserver/src/tenant.rs#L994-L1000

After this call, we import pg data, extract `initdb_lsn` from it and query safekeepers to get more WAL from compute, if there's any, using Lsn, based on `initdb_lsn` as a start lsn for these queries.
Safekeepers, on their side, do record this start lsn as an offset from where the WAL streaming should start and store WAL in the files based on this offset.

Later, if we want to restore pageserver entirely from safekeeper WAL, it's possible to do this similar way: create an empty timeline on pageserver with the needed IDs, make it query safekeeper for more WAL that it had stored from the precious wal streaming.

That would not work, if the Lsn offset is different: safekeepers will start streaming WAL from a different offset, WAL segments' checksums won't match and data inside that WAL would not match the expected on pageserver's side.
Example: https://neondb.slack.com/archives/C03H1K0PGKH/p1664971119442359

---------------

Turns out, that `initdb` does not produce the same output even when run from the same binaries.
Consider https://github.com/neondatabase/neon/pull/2589 PR that was built recently: it had produced `neondatabase/neon:2178` image that was tagged as `neondatabase/neon:latest` one after the build.

If you run things inside Docker image for it `docker run -it --rm neondatabase/neon:2178 bash`, it will output the following:
```
neon@8478c4e9b86a:~$ env LD_LIBRARY_PATH="/usr/local/v14/lib/" env DYLD_LIBRARY_PATH="/usr/local/v14/lib/" /usr/local/v14/bin/initdb -D ./pg14-initdb/ -U test_user -E utf8 --no-instructions --no-sync
... snip, successful operation, creates `pg14-initdb` directory

neon@8478c4e9b86a:~$ /usr/local/bin/pageserver_binutils ./pg14-initdb/global/pg_control
... snip
pg_initdb_lsn: 0/1696070, aligned: 0/1696070

neon@8478c4e9b86a:~$ /usr/local/bin/pageserver_binutils --version
Neon Pageserver binutils git-env:13f0e7a5b4a2ea1187955926e036d4ac57ed094c

neon@8478c4e9b86a:~$ env LD_LIBRARY_PATH="/usr/local/v14/lib/" env DYLD_LIBRARY_PATH="/usr/local/v14/lib/" /usr/local/v14/bin/initdb --version
initdb (PostgreSQL) 14.5

root@8478c4e9b86a:/data# file /usr/local/v14/bin/initdb
/usr/local/v14/bin/initdb: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=7846631cab9d142450aea3e6e8a5330944a9d291, for GNU/Linux 3.2.0, with debug_info, not stripped
```

Same image, after being deployed on `stage-ps-2`, outputs the following:

```
admin@zenith-us-stage-ps-2:~$ env LD_LIBRARY_PATH="/usr/local/v14/lib/" env DYLD_LIBRARY_PATH="/usr/local/v14/lib/" /usr/local/v14/bin/initdb -D ./pg14-initdb/ -U test_user -E utf8 --no-instructions --no-sync
... snip, successful operation, creates `pg14-initdb` directory

admin@zenith-us-stage-ps-2:~$ /usr/local/bin/pageserver_binutils ./pg14-initdb/global/pg_control
... snip
pg_initdb_lsn: 0/1696068, aligned: 0/1696068

admin@zenith-us-stage-ps-2:~$ /usr/local/bin/pageserver_binutils --version
Neon Pageserver binutils git-env:13f0e7a5b4a2ea1187955926e036d4ac57ed094c 

admin@zenith-us-stage-ps-2:~$ env LD_LIBRARY_PATH="/usr/local/v14/lib/" env DYLD_LIBRARY_PATH="/usr/local/v14/lib/" /usr/local/v14/bin/initdb --version
initdb (PostgreSQL) 14.5

admin@zenith-us-stage-ps-2:~$ file /usr/local/v14/bin/initdb
/usr/local/v14/bin/initdb: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=7846631cab9d142450aea3e6e8a5330944a9d291, for GNU/Linux 3.2.0, with debug_info, not stripped
```

Binary files and build hashes match, but their `pg_initdb_lsn` output is different for a couple of bytes.
With the tenant relocation and various other ways to dynamically switch environments for the timeline, at the current point, we cannot guarantee that `initdb_lsn` is identical hence cannot rely that safekeeper WAL restoration will ever work now.

**Comment by koivunej** [comment] 2023-07-17 14:02
Earlier this issue came up through https://neondb.slack.com/archives/C04KGFVUWUQ/p1688655397162369 where we discussed what is now https://github.com/neondatabase/neon/pull/4603#issuecomment-1632289619 and instead went with a different postgres version check in #4692.

Today we discussed it in the storage weekly as it's related to our upcoming disaster recovery [OKR](https://www.notion.so/neondatabase/Storage-OKRs-Q3-23-0bb6cc319388407eadf68a6c85a997f4?pvs=4#6228af5b2d254b11a5356453302e38f7) (private link).

If we really want to backup all at pageserver `initdb` creations, we could create a tar file out of the currently thrown out `initdb` directory [^1], and create a repository of `/initdbs/${tar_sha2-256}.tar` out of it in S3 and link to this hash from Timeline metadata (index_part.json directly or indirectly).

However, a question was raised from earlier discussions, would it make sense if **compute** ran the `initdb` as part of new tenant creation *and* backed up the `initdb` image stream it to safekeepers [^2]. Then we wouldn't have to do anything on pageserver than to accept that a new tenant and timeline has been created, which we'll later get through safekeepers? Alternatively computes could handle pushing the unique tar to S3, but that's one more hop.

@hlinnaka I think we need opinions or a recap of earlier discussions or links, here on which way should we go.

[^1]: Considerations for making a tar file light weight as to be near canonical for hashing purposes omitted. If we find that every second `initdb` produces a different result, then perhaps we could work on fixing that in `initdb`.
[^2]: Specifics left out, pageserver would have to be able to produce a image layer of `initdb` afterwards.

**Comment by arpad-m** [comment] 2023-09-14 15:47
Alternatively, we could just reuse different postgres initdb runs by unifying them after (storage commit hash, postgres version number): if there is an S3 entry already found, use it, otherwise upload one. race conditions are an obvious problem though, wondering how those can be addressed.

**Comment by arpad-m** [comment] 2023-09-14 17:48
Did some experiments with zstd dictionaries. I have three postgres initdb instances, in directories t0, t1, t2. Then i tarred each of the directories. The resulting sizes:

```
$ stat -c "%s %n" *tar
39628800 t0.tar
39628800 t1.tar
39628800 t2.tar
```

So around 38 MB. Then I ran normal zstd on them. Resulting sizes (no special parameters):

```
$ stat -c "%s %n" *zst
3610087 t0.tar.zst
3609645 t1.tar.zst
3609810 t2.tar.zst
```

This is a 10 fold decrease in storage size! Then I created a zstd dictionary on the t0 and t1 files. It gave some warnings:

```
$ zstd --train ../t0/* ../t1/* -o zst-dict
!  Warning : data size of samples too small for target dictionary size 
!  Samples should be about 100x larger than target dictionary size 
Trying 5 different sets of parameters                                          
WARNING: The maximum dictionary size 112640 is too large compared to the source size 11386! size(source)/size(dictionary) = 0.101083, but it should be >= 10! This may lead to a subpar dictionary! We recommend training on sources at least 10x, and preferably 100x the size of the dictionary! 
k=50                                                                           
d=8
f=20
steps=4
split=75
accel=1
Save dictionary of size 7812 into file zst-dict
```

Resulting sizes aren't really reduced significantly:

```
$ stat -c "%s %n" *zst
3624469 t0.tar.zst
3624207 t1.tar.zst
3624362 t2.tar.zst
```

For the last of the three files, there is a 0.4% reduction, while for the first two, there is a similarly small increase even.

Now I've tried using `bsdiff` on the tar files, and found great improvements:

```
$ bsdiff t0.tar t1.tar t0t1.bsdiff
$ bsdiff t0.tar t2.tar t0t2.bsdiff
$ stat -c "%s %n" *bsdiff
18759 t0t1.bsdiff
17777 t0t2.bsdiff
```

The diff is only 18 KB large! The only issue is that the bsdiff process takes 11 seconds. We would have to move it to a background process or something.

**Comment by arpad-m** [comment] 2023-09-14 22:00
Okay, with the prior comment in mind, we can store diffs cheaply, but we might not have to. The main open question I have would be: do we want to support per-tenant postgres system identifiers, or is it okay to share them? Depending on that, we could have different setups.

Let's assume we don't have per-tenant system identifiers, then the logic could look like:

1. look up S3 for given `(storage commit id, postgres version number`) tuple.
2. if .tar.gz found -> extract it, import it.
3. if tar.gz not found -> run `initdb`, upload result to S3
4. in both cases: store the sha hash of the corresponding .tar.gz in the `index_part.json` so that we can look it up during recovery.

We handle race conditions via hashing the .tar, and appending the hash to the name of the .tar file. That way, on a race condition, we simply upload multiple .tar.gz files. In step 1, if there is multiple matching tar.gz we take the one with the lowest number hash.

If we *do* want to have per-tenant system identifiers, we could either figure out a way to infuse it externally, say via setting it in the control file and WAL header (there should be no other place the system identifier is persisted to, right?). There is a [thread from 10 years ago](https://postgrespro.com/list/thread-id/1846052) about adding the ability to set the system identifier from `pg_resetxlog`. Or alternatively, we could slightly modify the steps: 

* 0. run `initdb`, tar up results.
* 1. look up S3 for given `(storage commit id, postgres version number`) tuple.
* 2. if .tar.gz found -> extract the .tar file and create bsdiff with result from 0. In a background task, compute bsdiff in a background task, should be a few kb, and upload it to S3 in timeline associated storage.
* 3. if tar.gz not found -> store `initdb` results to S3 directly
* 4. in both cases, compute the .tar.gz hash and store it in index_part.json. Also, store the info if bsdiff was ran or not.
* upon timeline deletion: also delete the corresponding bsdiff file.

The tough part here is that there is so much more complexity. Especially in step 2 what are we doing if the pageserver crashes or is killed during the process?

**Comment by hlinnaka** [comment] 2023-09-15 07:32
> So around 38 MB. Then I ran normal zstd on them. Resulting sizes (no special parameters):
> 
> $ stat -c "%s %n" *zst
> 3610087 t0.tar.zst
> 3609645 t1.tar.zst
> 3609810 t2.tar.zst

I think this is good enough. Storing 3 MB per tenant is insignificant in the grand scheme of things, there's not much point trying to optimize it further.

**Comment by hlinnaka** [comment] 2023-09-15 07:36
The `zstd --long` option makes a big difference:
```
/tmp$ tar c pgdata | zstd  | wc -c 
3851746
/tmp$ tar c pgdata | zstd --long  | wc -c 
1521159
```
And `--single-thread` saves a little too:
```
/tmp$ tar c pgdata | zstd --long --single-thread  | wc -c 
1502937
```

**Comment by arpad-m** [comment] 2023-09-15 13:22
@hlinnaka interesting insight about `--single-thread`. All three operations are within 10% of each other in terms of compression speed, and all very fast (around 0.1s). If uploading that is okay, let's do that :+1: .

**Comment by arpad-m** [comment] 2023-09-16 01:27
Some detailed comparison with brotli:

<details>

```
$ time cat t0.tar | zstd | wc -c
3610083

real    0m0,090s
user    0m0,085s
sys     0m0,077s
$ time cat t0.tar | zstd --long | wc -c
1398252

real    0m0,107s
user    0m0,077s
sys     0m0,092s
$ time cat t0.tar | brotli  | wc -c
1207586

real    0m14,625s
user    0m14,503s
sys     0m0,117s
$ time cat t0.tar | brotli  --large_window=27 | wc -c
1005311

real    0m13,655s
user    0m13,542s
sys     0m0,104s
$ time cat t0.tar | brotli -3 | wc -c
3238031

real    0m0,196s
user    0m0,123s
sys     0m0,077
$ time cat t0.tar | brotli -3 --large_window=27 | wc -c
1682209

real    0m0,187s
user    0m0,119s
sys     0m0,072s
$ time cat t0.tar | zstd -19 --long | wc -c
1106687

real    0m2,362s
user    0m2,263s
sys     0m0,130s
```

</details>


By default, brotli is way slower than zstd, but it also achieves the smallest result. At fast speeds, zstd is the best though, and only lies 30% above brotli's smallest result. Let's take zstd I'd say.

**Comment by koivunej** [comment] 2023-09-16 21:05
(Was just catching up on the latest progress here. Just as a note to myself later, `zstd` defaults to level 3, which is faster and smaller than gzip according to their compression speed vs ratio. I've always used 10 because that's near the middle :))

**Comment by arpad-m** [comment] 2023-09-17 16:43
Yeah from my point of view, the research phase is progressed far enough that the next step is a pull request (which I'm working on).

**Comment by petuhovskiy** [comment] 2023-10-02 14:27
Do we also want to restore historical initdb archives for all existing projects? I think it's important, because otherwise we will not be able to restore from WAL (#5282) for all projects created before this feature will be implemented. It can be a hard task to recover initdb result for old tenants, so we probably should finish #5390 first. WDYT?

**Comment by arpad-m** [comment] 2023-10-02 18:34
You are making a good point! I think we can use whatever method we use right now for the legacy databases created before the merging of #5390. Every database created after will be recoverable automatically though. Given that we are exponentially growing (at least that's the feeling I get), the legacy databases will quickly become a minority.

And we can always figure out something for them later on, I'm sure.

**Comment by hlinnaka** [comment] 2023-10-02 19:00
We can create a physical snapshot of existing databases, as of now, from the pageserver. That will allow us to recover from any issues that arise in the future, although it won't allow you to recover to an earlier point.

**Comment by arpad-m** [comment] 2023-10-03 00:09
You mean storing all the pages in on-disk format and then creating a tar file? That would be quite expensive in terms of data, but I suppose it would mean that we can then throw away the WAL older than those files, which is probably going to be larger than these snapshots.

**Comment by bayandin** [comment] 2023-11-14 11:41
Another example of a failure: https://github.com/neondatabase/neon/pull/5835

**Comment by arpad-m** [comment] 2023-11-23 18:17
With the merge of #5390, this is now fixed for all future projects/tenants. For the existing projects/tenants, we need to find something out still. Can this be closed now?

**Comment by koivunej** [comment] 2023-11-28 14:37
> For the existing projects/tenants, we need to find something out still.
Discussed earlier: base or fullbackup snapshot to s3, unsure which.

> Can this be closed now?
I think not: "initdb is unreproducable" as in the issue stands still. I think we could keep this open until we have solved the problem. #5892 will follow similar pattern of including initdb with the ingested wal.

**Closed** 2023-11-28 17:32 UTC
Labels: t/bug, c/storage/pageserver
