### ISSUE TITLE
`test_wal_backup[mock_s3]` is flaky

### ISSUE THREAD

**Issue by yeputons** [neondatabase/neon#2048] opened 2022-07-07 12:04 UTC
Example: https://app.circleci.com/pipelines/github/neondatabase/neon/7767/workflows/abf658db-1a9c-413c-bb4e-a2cfb74350a6/jobs/79743

```
Exception:             Run ['/tmp/zenith/bin/neon_local', 'pg', 'start', '--tenant-id', 'bc7f8041cdb247d1add2204dcec9e797', '--port=15138', 'test_safekeepers_wal_backup_pg_node'] failed:
              stdout: Starting existing postgres test_safekeepers_wal_backup_pg_node...
Safekeepers synced on 0/4A82038
Extracting base backup to create postgres instance: path=/tmp/test_output/test_wal_backup[mock_s3]/repo/pgdatadirs/tenants/bc7f8041cdb247d1add2204dcec9e797/test_safekeepers_wal_backup_pg_node port=15138

              stderr: command failed: extracting base backup failed

Caused by:
    0: failed to iterate over archive
    1: db error: ERROR: Timed out while waiting for WAL record at LSN 0/4A82038 to arrive, last_record_lsn 0/48ED428 disk consistent LSN=0/1696628
    2: ERROR: Timed out while waiting for WAL record at LSN 0/4A82038 to arrive, last_record_lsn 0/48ED428 disk consistent LSN=0/1696628
subprocess.CalledProcessError: Command '['/tmp/zenith/bin/neon_local', 'pg', 'start', '--tenant-id', 'bc7f8041cdb247d1add2204dcec9e797', '--port=15138', 'test_safekeepers_wal_backup_pg_node']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:
test_runner/batch_others/test_wal_acceptor.py:502: in test_wal_backup
    pg.stop_and_destroy().create_start('test_safekeepers_wal_backup')
test_runner/fixtures/neon_fixtures.py:1730: in create_start
    self.create(
test_runner/fixtures/neon_fixtures.py:1624: in start
    run_result = self.env.neon_cli.pg_start(self.node_name,
test_runner/fixtures/neon_fixtures.py:1230: in pg_start
    res = self.raw_cli(args)
test_runner/fixtures/neon_fixtures.py:970: in raw_cli
    raise Exception(msg) from subprocess.CalledProcessError(res.returncode,
E   Exception:             Run ['/tmp/zenith/bin/neon_local', 'pg', 'start', '--tenant-id', 'bc7f8041cdb247d1add2204dcec9e797', '--port=15138', 'test_safekeepers_wal_backup_pg_node'] failed:
E                 stdout: Starting existing postgres test_safekeepers_wal_backup_pg_node...
E   Safekeepers synced on 0/4A82038
E   Extracting base backup to create postgres instance: path=/tmp/test_output/test_wal_backup[mock_s3]/repo/pgdatadirs/tenants/bc7f8041cdb247d1add2204dcec9e797/test_safekeepers_wal_backup_pg_node port=15138
E   
E                 stderr: command failed: extracting base backup failed
E   
E   Caused by:
E       0: failed to iterate over archive
E       1: db error: ERROR: Timed out while waiting for WAL record at LSN 0/4A82038 to arrive, last_record_lsn 0/48ED428 disk consistent LSN=0/1696628
E       2: ERROR: Timed out while waiting for WAL record at LSN 0/4A82038 to arrive, last_record_lsn 0/48ED428 disk consistent LSN=0/1696628
```

**Comment by yeputons** [comment] 2022-07-08 12:58
Another one: https://app.circleci.com/pipelines/github/neondatabase/neon/7824/workflows/e97c21e5-6c7f-498a-9f0c-f1289fed6c06/jobs/80328

Slightly different LSNs:

```
Exception:             Run ['/tmp/zenith/bin/neon_local', 'pg', 'start', '--tenant-id', 'ab520ccf24ad498791f2cf78e13c6c33', '--port=16095', 'test_safekeepers_wal_backup_pg_node'] failed:
              stdout: Starting existing postgres test_safekeepers_wal_backup_pg_node...
Safekeepers synced on 0/4A82070
Extracting base backup to create postgres instance: path=/tmp/test_output/test_wal_backup[mock_s3]/repo/pgdatadirs/tenants/ab520ccf24ad498791f2cf78e13c6c33/test_safekeepers_wal_backup_pg_node port=16095

              stderr: command failed: extracting base backup failed

Caused by:
    0: failed to iterate over archive
    1: db error: ERROR: Timed out while waiting for WAL record at LSN 0/4A82070 to arrive, last_record_lsn 0/49503F0 disk consistent LSN=0/1696628
    2: ERROR: Timed out while waiting for WAL record at LSN 0/4A82070 to arrive, last_record_lsn 0/49503F0 disk consistent LSN=0/1696628
subprocess.CalledProcessError: Command '['/tmp/zenith/bin/neon_local', 'pg', 'start', '--tenant-id', 'ab520ccf24ad498791f2cf78e13c6c33', '--port=16095', 'test_safekeepers_wal_backup_pg_node']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:
test_runner/batch_others/test_wal_acceptor.py:502: in test_wal_backup
    pg.stop_and_destroy().create_start('test_safekeepers_wal_backup')
test_runner/fixtures/neon_fixtures.py:1741: in create_start
    self.create(
test_runner/fixtures/neon_fixtures.py:1635: in start
    run_result = self.env.neon_cli.pg_start(self.node_name,
test_runner/fixtures/neon_fixtures.py:1241: in pg_start
    res = self.raw_cli(args)
test_runner/fixtures/neon_fixtures.py:981: in raw_cli
    raise Exception(msg) from subprocess.CalledProcessError(res.returncode,
E   Exception:             Run ['/tmp/zenith/bin/neon_local', 'pg', 'start', '--tenant-id', 'ab520ccf24ad498791f2cf78e13c6c33', '--port=16095', 'test_safekeepers_wal_backup_pg_node'] failed:
E                 stdout: Starting existing postgres test_safekeepers_wal_backup_pg_node...
E   Safekeepers synced on 0/4A82070
E   Extracting base backup to create postgres instance: path=/tmp/test_output/test_wal_backup[mock_s3]/repo/pgdatadirs/tenants/ab520ccf24ad498791f2cf78e13c6c33/test_safekeepers_wal_backup_pg_node port=16095
E   
E                 stderr: command failed: extracting base backup failed
E   
E   Caused by:
E       0: failed to iterate over archive
E       1: db error: ERROR: Timed out while waiting for WAL record at LSN 0/4A82070 to arrive, last_record_lsn 0/49503F0 disk consistent LSN=0/1696628
E       2: ERROR: Timed out while waiting for WAL record at LSN 0/4A82070 to arrive, last_record_lsn 0/49503F0 disk consistent LSN=0/1696628
```

**Comment by arssher** [comment] 2022-07-15 17:56
Yes, looking.

**Comment by arssher** [comment] 2022-07-18 11:32
So, the last two are caused by 
```
        assert!(commit_lsn >= self.inmem.commit_lsn);
``` 
addressed by https://github.com/neondatabase/neon/pull/2109

I don't see any particular problem with the first two. It just looks like pageserver couldn't chew full segment (16MB) in 1 minute of `Timed out while waiting for WAL record at LSN 0/4A82038` timeout. In this test we insert a bunch of data to create full segment and then immediately recreate compute -- pageserver must be caught up to provide basebackup. In both cases it was pretty close, reaching about 13-14MB on the moment of timeout. Not sure what is the best thing to do here, 1 minute limitation is already pretty conservative... I think we need to check whether it is really so slow and why, if so; probably in github runners it got better.

**Closed** 2022-08-08 15:15 UTC
Labels: a/test

**Comment by arssher** [comment] 2022-08-08 15:16
Most failures were fixed by https://github.com/neondatabase/neon/commit/a69fdb0e8e64ae9482b1a78a546cdd4d3ec6d4ab , the rest were caused by slow runners and don't seem to repeat on github runners.
