### ISSUE TITLE
tenant can not be restarted after 500 MB dump restore

### ISSUE THREAD

**Issue by gchiappe** [neondatabase/neon#1174] opened 2022-01-24 19:42 UTC
after a complex schema restoration of about 500MB the tenant cannot be started after a clean stop and reboot of the host.

The following output is given by the Zenith CLI:

```
./target/release/zenith pg start main
Starting existing postgres main...
Safekeepers synced on 4/822AD0A8
Extracting base backup to create postgres instance: path=.zenith/pgdatadirs/tenants/2ccd2480e6236acd2f1768e75c1aecd2/main port=55432
command failed: extracting base backup failed: failed to iterate over archive: db error: ERROR: Timed out while waiting for WAL record at LSN 4/822AD0A8 to arrive, last_record_lsn 4/72445828 disk consistent LSN=4/72445828: ERROR: Timed out while waiting for WAL record at LSN 4/822AD0A8 to arrive, last_record_lsn 4/72445828 disk consistent LSN=4/72445828
```

The following relevant settings have been used:

- build type: release
- shared_buffers=8GB
- wal_keep_size=1GB

More information about folder sizes inside the `.zenith` folder:

![image](https://user-images.githubusercontent.com/3721685/150852657-922d6063-2ca0-44d3-9df6-d92d267faa3f.png)

**Comment by knizhnik** [comment] 2022-01-27 12:27
Results at my note:

Vanilla (shared_buffers=2GB):
real	10m43,577s
user	0m16,757s
sys	0m4,381s

Zenith (shared_buffers=2GB, max_wal_size=10GB, wal_log_hints=off, disabled back pressure):
real	16m49,722s
user	0m18,223s
sys	0m5,917s

Zenith (shared_buffers=1MB, file_cache_size=16384, max_wal_size=10GB, wal_log_hints=off, disabled back pressure):
real	25m34,688s
user	0m18,118s
sys	0m5,864s

So Zenith is 1.5 times slower than Vanilla with the same shared buffers (which are still smaller than DB size)
and 2.5 times slower than Zenith with small shared buffers but local file cache.
It seems to be acceptable result, especially taken in account that all Zenith components are lauched at the same notebook with limited resources.

**Comment by hlinnaka** [comment] 2022-01-27 14:38
Performance is one thing, but the issue here was about not being able to restart the compute node, after shutting it down. That sounds like a bug.

**Comment by knizhnik** [comment] 2022-01-27 15:55
Sorry, but I was not able to reproduce the problem.
I wonder how database was restarted? Using CLI?
I did the following:
```
./target/release/zenith pg stop main
./target/release/zenith stop
./target/release/zenith start
./target/release/zenith pg start main
```
and there is no any problem. All operations are performed fast enough.
Actually size of basebackup (use to launch new node) doesn't depend on database size and is small enough. So the only reason why it may be terminated by timeout is that pageserver is busy with some other work (GC/checkpointer/...). Or there is some error. In this case it will be useful to inspect logs...

**Comment by kelvich** [comment] 2022-01-28 13:08
I've played with restoration of that dump on our staging and noticed that pg_restore generated 30GB of WAL. Disabling `wal_log_hints` reduced it to 10GB, but that did not affected total run time. Created an issue to fix default settings: https://github.com/zenithdb/console/issues/562

### With wal_log_hints
WAL size ~= 30 GB
<img width="1253" alt="Screen Shot 2022-01-28 at 15 52 17" src="https://user-images.githubusercontent.com/284219/151551274-0e160b58-aba6-4d7f-a5a9-c56cca53342c.png">

### Without wal_log_hint
WAL size ~= 10 GB
<img width="1210" alt="Screen Shot 2022-01-28 at 15 46 51" src="https://user-images.githubusercontent.com/284219/151551339-2fcd57a8-5f9e-47a8-8dbc-098aa76dfb46.png">

So still it is few times slower than a local installation, but main metrics looks fine -- e.g. getpage ratio is reasonably low (average ratio was 1k/sec; that can cause somewhat 10-20% delay, but not more) . For further investigation I think we need to install pg_wait_sampling and collect wait times and compare them with a usual postgres.

**Comment by gchiappe** [comment] 2022-01-28 16:24
> Sorry, but I was not able to reproduce the problem. I wonder how database was restarted? Using CLI? I did the following:
> 
> ```
> ./target/release/zenith pg stop main
> ./target/release/zenith stop
> ./target/release/zenith start
> ./target/release/zenith pg start main
> ```
> 
> and there is no any problem. All operations are performed fast enough. Actually size of basebackup (use to launch new node) doesn't depend on database size and is small enough. So the only reason why it may be terminated by timeout is that pageserver is busy with some other work (GC/checkpointer/...). Or there is some error. In this case it will be useful to inspect logs...

Yes, the DB was restarted cleanly using CLI with same commands that you have issued, I don't have that commit locally anymore nor recall what commit # was but I will try again with the settings you posted and latest commit

**Comment by knizhnik** [comment] 2022-01-28 16:41
> I've played with restoration of that dump on our staging and noticed that pg_restore generated 30GB of WAL. Disabling `wal_log_hints` reduced it to 10GB, but that did not affected total run time. 

This is actually very strange.  Because at notebook with 2Gb shared_buffer I was able to load data in just 16 minutes. And it is with relatively slow SSD which speed is ~5 time slower that what I see at EC2 instances.

The fact that reducing WAL traffic 3 times doesn't significantly reduce load time make me think that it is mostly limited by get_page latency, although 2000 requests per second much smaller (~10 times) than maximal number of syscalls/per second.

**Comment by knizhnik** [comment] 2022-01-29 05:52
With 256Mb shared_buffer load time at my notebook is 58 minutes, comparing with 16 minutes with 2GB shared buffers. So looks like there is strick dependency between number get_page requests and load 
```
time.pageserver_smgr_query_time_sum{smgr_query_type="get_page_at_lsn"} 10815.552459505194
pageserver_smgr_query_time_count{smgr_query_type="get_page_at_lsn"} 4946121
```

**Comment by shanyp** [comment] 2023-02-23 11:25
@knizhnik is this still relevant or can we close it ?

**Comment by knizhnik** [comment] 2023-02-23 13:42
It was not my ticket.
I do not see any new problem here - it is well known fact that get_page_at_lsn can be a bottleneck which several times decrease Nein speed comparing with standalone Postgres. But since the time of reporting this issue we have added prfetch which should speedup many workloads (including vacuum and buldig indexes).

**Comment by shanyp** [comment] 2023-02-23 13:50
so do we benefit from having this one open if there are no actionable tasks for it?

@kelvich WDYT ?

**Comment by kelvich** [comment] 2023-02-24 08:28
yes, let's close. Original issue was solved

**Closed** 2023-02-25 07:33 UTC
Labels: t/bug, p/self-hosted, c/storage
