### ISSUE TITLE
Deleting a timeline leads to a permanent failure of the activity monitor with a storm of error messages

### ISSUE THREAD

**Issue by alexanderlaw** [neondatabase/neon#5754] opened 2023-11-01 12:00 UTC
## Steps to reproduce
export RUST_LOG=DEBUG 

cargo neon init --force
cargo neon start
ten="10000000000000000000000000000001"
cargo neon tenant create --tenant-id=$ten --pg-version 16 --set-default
cargo neon endpoint start main --pg-version 16
sleep 4
tim=$(curl -s "http://127.0.0.1:9898/v1/tenant/$ten/timeline" | jq -r ".[0].timeline_id")
curl -s "http://127.0.0.1:9898/v1/tenant/$ten/timeline/$tim"; echo ""
echo "Deleting timeline $tim..."
curl -X DELETE "http://127.0.0.1:9898/v1/tenant/$ten/timeline/$tim"; echo ""
sleep 80
ls -lh .neon/pageserver_1/pageserver.log
cargo neon stop

## Result
```
...
Deleting timeline 06f0c9241d2f2da32286d71ee8da3248...
null
-rw-rw-r-- 1 law law 794M Nov  1 14:23 .neon/pageserver_1/pageserver.log

```

## Logs, links
.neon/pageserver_1/pageserver.log contains:
```
...
2023-11-01T11:21:53.067105Z DEBUG Starting task 'timeline_delete'
2023-11-01T11:21:53.067123Z  INFO request{method=DELETE path=/v1/tenant/10000000000000000000000000000001/timeline/06f0c9241d2f2da32286d71ee8da3248 request_id=1ed1402f-240f-417c-a8f7-639e77a87848}: Request handled, status: 202 Accepted
2023-11-01T11:21:53.086842Z DEBUG Task 'timeline_delete' exited normally
...
2023-11-01T11:22:49.027536Z DEBUG Starting task 'serving compute connection task'
2023-11-01T11:22:49.027610Z DEBUG page_service_conn_main{peer_addr=127.0.0.1:40462}: SSL requested
2023-11-01T11:22:49.027857Z DEBUG page_service_conn_main{peer_addr=127.0.0.1:40462}:process_query: process query "pagestream 10000000000000000000000000000001 06f0c9241d2f2da32286d71ee8da3248"
2023-11-01T11:22:49.027941Z ERROR page_service_conn_main{peer_addr=127.0.0.1:40462}: query handler for 'pagestream 10000000000000000000000000000001 06f0c9241d2f2da32286d71ee8da3248' failed: Timeline 10000000000000000000000000000001/06f0c9241d2f2da32286d71ee8da3248 was not found

Stack backtrace:
   0: <T as core::convert::Into<U>>::into
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/convert/mod.rs:716:9
      anyhow::kind::Trait::new
             at .../rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/anyhow-1.0.71/src/kind.rs:91:9
      pageserver::page_service::PageServerHandler::handle_pagerequests::{{closure}}::{{closure}}::{{closure}}
             at .../neon/pageserver/src/page_service.rs:406:26
      core::result::Result<T,E>::map_err
             at .../cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/result.rs:829:27
      pageserver::page_service::PageServerHandler::handle_pagerequests::{{closure}}::{{closure}}
             at .../neon/pageserver/src/page_service.rs:404:24
   1: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at .../rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
   2: pageserver::page_service::PageServerHandler::handle_pagerequests::{{closure}}
             at .../neon/pageserver/src/page_service.rs:374:5
      <pageserver::page_service::PageServerHandler as postgres_backend::Handler<IO>>::process_query::{{closure}}::{{closure}}
             at .../neon/pageserver/src/page_service.rs:966:18
...
2023-11-01T11:22:49.382614Z DEBUG Task 'serving compute connection task' exited normally
2023-11-01T11:22:49.382947Z DEBUG accepted connection from 127.0.0.1:40468
2023-11-01T11:22:49.382970Z DEBUG Starting task 'serving compute connection task'
2023-11-01T11:22:49.382998Z DEBUG page_service_conn_main{peer_addr=127.0.0.1:40468}: SSL requested
2023-11-01T11:22:49.383110Z DEBUG page_service_conn_main{peer_addr=127.0.0.1:40468}:process_query: process query "pagestream 10000000000000000000000000000001 06f0c9241d2f2da32286d71ee8da3248"
2023-11-01T11:22:49.383172Z ERROR page_service_conn_main{peer_addr=127.0.0.1:40468}: query handler for 'pagestream 10000000000000000000000000000001 06f0c9241d2f2da32286d71ee8da3248' failed: Timeline 10000000000000000000000000000001/06f0c9241d2f2da32286d71ee8da3248 was not found
...
```

$ grep 'ERROR page_service_conn_main' .neon/pageserver_1/pageserver.log | wc -l
55597

.neon/endpoints/main/compute.log contains:
```
...
2023-11-01T11:22:47.589499Z DEBUG preparing query s115: SELECT state, to_char(state_change, 'YYYY-MM-DD"T"HH24:MI:SS.US"Z"') AS state_change
                         FROM pg_stat_activity
                         WHERE backend_type = 'client backend'
                            AND pid != pg_backend_pid()
                            AND usename != 'cloud_admin';
2023-11-01T11:22:47.593639Z DEBUG executing statement s115 with parameters: []
2023-11-01T11:22:48.096598Z DEBUG preparing query s116: SELECT state, to_char(state_change, 'YYYY-MM-DD"T"HH24:MI:SS.US"Z"') AS state_change
                         FROM pg_stat_activity
                         WHERE backend_type = 'client backend'
                            AND pid != pg_backend_pid()
                            AND usename != 'cloud_admin';
2023-11-01T11:22:48.101520Z DEBUG executing statement s116 with parameters: []
2023-11-01T11:22:48.604602Z DEBUG preparing query s117: SELECT state, to_char(state_change, 'YYYY-MM-DD"T"HH24:MI:SS.US"Z"') AS state_change
                         FROM pg_stat_activity
                         WHERE backend_type = 'client backend'
                            AND pid != pg_backend_pid()
                            AND usename != 'cloud_admin';
2023-11-01T11:22:48.608734Z DEBUG executing statement s117 with parameters: []
2023-11-01T11:22:49.111724Z DEBUG preparing query s118: SELECT state, to_char(state_change, 'YYYY-MM-DD"T"HH24:MI:SS.US"Z"') AS state_change
                         FROM pg_stat_activity
                         WHERE backend_type = 'client backend'
                            AND pid != pg_backend_pid()
                            AND usename != 'cloud_admin';
2023-11-01T11:22:49.116217Z DEBUG executing statement s118 with parameters: []
2023-11-01 11:22:49.382 GMT [2665739] LOG:  [NEON_SMGR] libpagestore: connected to 'postgresql://no_user@127.0.0.1:64000'
2023-11-01 11:22:49.382 GMT [2665739] LOG:  [NEON_SMGR] dropping connection to page server due to error
2023-11-01 11:22:49.382 GMT [2665739] LOG:  [NEON_SMGR] pageserver_send disconnect because failed to send page request (try to reconnect): ERROR:  Timeline 10000000000000000000000000000001/06f0c9241d2f2da32286d71ee8da3248 was not found
    no COPY in progress
2023-11-01 11:22:49.383 GMT [2665739] LOG:  [NEON_SMGR] libpagestore: connected to 'postgresql://no_user@127.0.0.1:64000'
2023-11-01 11:22:49.383 GMT [2665739] LOG:  [NEON_SMGR] dropping connection to page server due to error
2023-11-01 11:22:49.383 GMT [2665739] LOG:  [NEON_SMGR] pageserver_send disconnect because failed to send page request (try to reconnect): ERROR:  Timeline 10000000000000000000000000000001/06f0c9241d2f2da32286d71ee8da3248 was not found
    no COPY in progress
...
```

That is, one minute since the timeline deletion, the activity monitor starts to get connection errors due to absence of the target timeline and tries to reconnect immediately (without waiting for 500 ms), that leads to flooding of server logs.

**Comment by hlinnaka** [comment] 2024-06-11 20:53
I cannot reproduce this now. There's only one error in the compute log when the timeline is deleted:
```
2024-06-11T20:49:32.861091Z DEBUG executing statement s473 with parameters: []    
2024-06-11T20:49:32.861955Z DEBUG preparing query s474: select count(*) from pg_stat_replication where application_name != 'walproposer';    
2024-06-11T20:49:32.862965Z DEBUG executing statement s474 with parameters: []    
2024-06-11T20:49:32.863776Z DEBUG preparing query s475: select count(*) from pg_stat_subscription where pid is not null;    
2024-06-11T20:49:32.864246Z DEBUG executing statement s475 with parameters: []    
2024-06-11T20:49:32.864812Z DEBUG preparing query s476: select count(*) from pg_stat_activity where backend_type = 'autovacuum worker'    
2024-06-11T20:49:32.865568Z DEBUG executing statement s476 with parameters: []    
PG:2024-06-11 20:49:33.146 GMT [321337] LOG:  [NEON_SMGR] [shard 0] libpagestore: connected to 'postgresql://no_user@localhost:64000' with protocol version 2
PG:2024-06-11 20:49:33.146 GMT [321337] ERROR:  [NEON_SMGR] [shard 0] could not read block 0 in rel 1664/0/2672.0 from page server at lsn 0/014F1380
PG:2024-06-11 20:49:33.146 GMT [321337] DETAIL:  page server returned error: Not found: Timeline 10000000000000000000000000000001/d1e61f7fcf2afd6b42cb436e364dd1dc was not found
2024-06-11T20:49:33.366348Z DEBUG preparing query s477: SELECT state, to_char(state_change, 'YYYY-MM-DD"T"HH24:MI:SS.US"Z"') AS state_change
                FROM pg_stat_activity
                    WHERE backend_type = 'client backend'
                    AND pid != pg_backend_pid()
                    AND usename != 'cloud_admin';    
2024-06-11T20:49:33.367486Z DEBUG executing statement s477 with parameters: []    
2024-06-11T20:49:33.368316Z DEBUG preparing query s478: select count(*) from pg_stat_replication where application_name != 'walproposer';    
2024-06-11T20:49:33.369192Z DEBUG executing statement s478 with parameters: []    
2024-06-11T20:49:33.370386Z DEBUG preparing query s479: select count(*) from pg_stat_subscription where pid is not null;    
2024-06-11T20:49:33.371035Z DEBUG executing statement s479 with parameters: []    
2024-06-11T20:49:33.371935Z DEBUG preparing query s480: select count(*) from pg_stat_activity where backend_type = 'autovacuum worker'    
2024-06-11T20:49:33.372918Z DEBUG executing statement s480 with parameters: []    
```
and the logfile has a reasonable size:
```
Deleting timeline d1e61f7fcf2afd6b42cb436e364dd1dc...
null
-rw-r--r-- 1 heikki heikki 1.2M Jun 11 23:49 .neon/pageserver_1/pageserver.log
```

I'm not sure if we've done something that fixed this, or if the script just doesn't reproduce it anymore. I'll close this, but let's re-open if we get more reports or other information.

P.S. the repro script was missing `endpoint create` step. Here are the full steps I used:
```
export RUST_LOG=DEBUG

cargo neon init
cargo neon start
ten="10000000000000000000000000000001"
cargo neon tenant create --tenant-id=$ten --pg-version 16 --set-default
cargo neon endpoint create main --pg-version 16
cargo neon endpoint start main
sleep 4
tim=$(curl -s "http://127.0.0.1:9898/v1/tenant/$ten/timeline" | jq -r ".[0].timeline_id")
curl -s "http://127.0.0.1:9898/v1/tenant/$ten/timeline/$tim"; echo ""
echo "Deleting timeline $tim..."
curl -X DELETE "http://127.0.0.1:9898/v1/tenant/$ten/timeline/$tim"; echo ""
sleep 80
ls -lh .neon/pageserver_1/pageserver.log
cargo neon stop
```

**Closed by hlinnaka** 2024-06-11 20:53 UTC
Labels: t/bug
