### ISSUE TITLE
test_pageserver_catchup_while_compute_down is flaky

### ISSUE THREAD

**Issue by arssher** [neondatabase/neon#1666] opened 2022-05-10 18:40 UTC
e.g. https://app.circleci.com/pipelines/github/neondatabase/neon/6216/workflows/8050c2ce-5a25-4acd-afa0-87bb34f208fd/jobs/61880/tests

Manifests as
```
test_runner/batch_others/test_pageserver_catchup.py:38: in test_pageserver_catchup_while_compute_down
    cur.execute('''
E   psycopg2.errors.QueryCanceled: canceling statement due to statement timeout
```

This seems to happen because compute goes to pageserver when this is not expected. 75002ad tried to fix that, but didn't help.

**Comment by petuhovskiy** [comment] 2022-05-10 20:26
Duplicate of https://github.com/neondatabase/neon/issues/1517

**Closed by petuhovskiy** 2022-05-10 20:26 UTC
Labels: c/storage/safekeeper, c/storage/pageserver
