### ISSUE TITLE
DATA CORRUPTION: deserialize error while reading from delta layer

### ISSUE THREAD

**Issue by LizardWizzard** [neondatabase/neon#1606] opened 2022-05-02 14:28 UTC
Happened in staging environment on pageserver 2.

The first spotted problem was panic in compaction thread:

```
May 02 00:42:49 zenith-us-stage-ps-2.local pageserver[27329]: thread 'Compactor thread' panicked at 'unsorted input', pageserver/src/layered_repository/disk_btree.rs:448:13
May 02 00:42:49 zenith-us-stage-ps-2.local pageserver[27329]: stack backtrace:
May 02 00:42:50 zenith-us-stage-ps-2.local pageserver[27329]:    0: rust_begin_unwind
May 02 00:42:50 zenith-us-stage-ps-2.local pageserver[27329]:              at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:498:5
May 02 00:42:50 zenith-us-stage-ps-2.local pageserver[27329]:    1: core::panicking::panic_fmt
May 02 00:42:50 zenith-us-stage-ps-2.local pageserver[27329]:              at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/panicking.rs:107:14
May 02 00:42:50 zenith-us-stage-ps-2.local pageserver[27329]:    2: pageserver::layered_repository::disk_btree::DiskBtreeBuilder<W,_>::append
May 02 00:42:50 zenith-us-stage-ps-2.local pageserver[27329]:              at /home/circleci/project/pageserver/src/layered_repository/disk_btree.rs:448:13
May 02 00:42:50 zenith-us-stage-ps-2.local pageserver[27329]:    3: pageserver::layered_repository::delta_layer::DeltaLayerWriter::put_value
May 02 00:42:50 zenith-us-stage-ps-2.local pageserver[27329]:              at /home/circleci/project/pageserver/src/layered_repository/delta_layer.rs:649:9
May 02 00:42:50 zenith-us-stage-ps-2.local pageserver[27329]:    4: pageserver::layered_repository::LayeredTimeline::compact_level0
May 02 00:42:50 zenith-us-stage-ps-2.local pageserver[27329]:              at /home/circleci/project/pageserver/src/layered_repository.rs:1992:13
May 02 00:42:50 zenith-us-stage-ps-2.local pageserver[27329]:    5: pageserver::layered_repository::LayeredTimeline::compact
May 02 00:42:50 zenith-us-stage-ps-2.local pageserver[27329]:              at /home/circleci/project/pageserver/src/layered_repository.rs:1846:13
May 02 00:42:50 zenith-us-stage-ps-2.local pageserver[27329]:    6: <pageserver::layered_repository::LayeredRepository as pageserver::repository::Repository>::compaction_iteration
May 02 00:42:50 zenith-us-stage-ps-2.local pageserver[27329]:              at /home/circleci/project/pageserver/src/layered_repository.rs:348:21
May 02 00:42:50 zenith-us-stage-ps-2.local pageserver[27329]:    7: pageserver::tenant_threads::compact_loop_ext
May 02 00:42:50 zenith-us-stage-ps-2.local pageserver[27329]:              at /home/circleci/project/pageserver/src/tenant_threads.rs:36:9
May 02 00:42:50 zenith-us-stage-ps-2.local pageserver[27329]:    8: pageserver::tenant_threads::compact_loop
May 02 00:42:50 zenith-us-stage-ps-2.local pageserver[27329]:              at /home/circleci/project/pageserver/src/tenant_threads.rs:15:23
May 02 00:42:50 zenith-us-stage-ps-2.local pageserver[27329]:    9: pageserver::tenant_mgr::activate_tenant::{{closure}}
May 02 00:42:50 zenith-us-stage-ps-2.local pageserver[27329]:              at /home/circleci/project/pageserver/src/tenant_mgr.rs:248:25
May 02 00:42:50 zenith-us-stage-ps-2.local pageserver[27329]:   10: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
May 02 00:42:50 zenith-us-stage-ps-2.local pageserver[27329]:              at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/panic/unwind_safe.rs:271:9
May 02 00:42:50 zenith-us-stage-ps-2.local pageserver[27329]:   11: std::panicking::try::do_call
May 02 00:42:50 zenith-us-stage-ps-2.local pageserver[27329]:              at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:406:40
May 02 00:42:50 zenith-us-stage-ps-2.local pageserver[27329]:   12: std::panicking::try
May 02 00:42:50 zenith-us-stage-ps-2.local pageserver[27329]:              at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:370:19
May 02 00:42:50 zenith-us-stage-ps-2.local pageserver[27329]:   13: std::panic::catch_unwind
May 02 00:42:50 zenith-us-stage-ps-2.local pageserver[27329]:              at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panic.rs:133:14
May 02 00:42:50 zenith-us-stage-ps-2.local pageserver[27329]:   14: pageserver::thread_mgr::thread_wrapper
May 02 00:42:50 zenith-us-stage-ps-2.local pageserver[27329]:              at /home/circleci/project/pageserver/src/thread_mgr.rs:221:18
May 02 00:42:50 zenith-us-stage-ps-2.local pageserver[27329]:   15: pageserver::thread_mgr::spawn::{{closure}}
May 02 00:42:50 zenith-us-stage-ps-2.local pageserver[27329]:              at /home/circleci/project/pageserver/src/thread_mgr.rs:173:13
May 02 00:42:50 zenith-us-stage-ps-2.local pageserver[27329]: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
May 02 00:42:50 zenith-us-stage-ps-2.local pageserver[27329]: 2022-05-02T00:42:50.567408Z ERROR Shutting down: thread 'Compactor thread' panicked: Any { .. }
02 00:42:50 zenith-us-stage-ps-2.local pageserver[27329]: 2022-05-02T00:42:50.568370Z  INFO waiting for libpq endpoint thread to shut down
```

Panic in compaction thread caused pageserver to shutdown. That was fixed in #1622 and more details to thread errors were added in #1618. Panic was replaced by an error in #1612. 

After that pageserver was restarted deserialize error started to appear:

```
 2022-05-03T20:58:29.729152Z ERROR compact loop terminated with error: deserialize error
 Stack backtrace:
    0: <core::result::Result<T,F> as core::ops::try_trait::FromResidual<core::result::Result<core::convert::Infallible,E>>>::from_residual
              at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/result.rs:1911:27
       pageserver::layered_repository::delta_layer::DeltaValueIter::next_res
              at /home/circleci/project/pageserver/src/layered_repository/delta_layer.rs:794:23
       <pageserver::layered_repository::delta_layer::DeltaValueIter as core::iter::traits::iterator::Iterator>::next
              at /home/circleci/project/pageserver/src/layered_repository/delta_layer.rs:754:9
    1: <alloc::boxed::Box<I,A> as core::iter::traits::iterator::Iterator>::next
              at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/alloc/src/boxed.rs:1628:9
       itertools::kmerge_impl::HeadTail<I>::next
              at /home/circleci/.cargo/registry/src/github.com-1ecc6299db9ec823/itertools-0.10.3/src/kmerge_impl.rs:42:29
       <itertools::kmerge_impl::KMergeBy<I,F> as core::iter::traits::iterator::Iterator>::next
              at /home/circleci/.cargo/registry/src/github.com-1ecc6299db9ec823/itertools-0.10.3/src/kmerge_impl.rs:206:42
    2: pageserver::layered_repository::LayeredTimeline::compact_level0
              at /home/circleci/project/pageserver/src/layered_repository.rs:1982:18
       pageserver::layered_repository::LayeredTimeline::compact
              at /home/circleci/project/pageserver/src/layered_repository.rs:1859:13
    3: <pageserver::layered_repository::LayeredRepository as pageserver::repository::Repository>::compaction_iteration
              at /home/circleci/project/pageserver/src/layered_repository.rs:348:21
    4: pageserver::tenant_threads::compact_loop_ext
              at /home/circleci/project/pageserver/src/tenant_threads.rs:36:9
       pageserver::tenant_threads::compact_loop
              at /home/circleci/project/pageserver/src/tenant_threads.rs:15:23
    5: pageserver::tenant_mgr::activate_tenant::{{closure}}
              at /home/circleci/project/pageserver/src/tenant_mgr.rs:248:25
       <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
              at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/panic/unwind_safe.rs:271:9
       std::panicking::try::do_call
              at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:406:40
       std::panicking::try
              at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:370:19
       std::panic::catch_unwind
              at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panic.rs:133:14
       pageserver::thread_mgr::thread_wrapper
              at /home/circleci/project/pageserver/src/thread_mgr.rs:223:18
    6: pageserver::thread_mgr::spawn::{{closure}}
              at /home/circleci/project/pageserver/src/thread_mgr.rs:175:13
       std::sys_common::backtrace::__rust_begin_short_backtrace
              at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/sys_common/backtrace.rs:123:18
    7: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}
              at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/thread/mod.rs:484:17
       <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
              at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/panic/unwind_safe.rs:271:9
       std::panicking::try::do_call
              at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:406:40
       std::panicking::try
              at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:370:19
       std::panic::catch_unwind
              at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panic.rs:133:14
       std::thread::Builder::spawn_unchecked::{{closure}}
              at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/thread/mod.rs:483:30
       core::ops::function::FnOnce::call_once{{vtable.shim}}
              at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/ops/function.rs:227:5
    8: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
              at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/alloc/src/boxed.rs:1694:9
       <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
              at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/alloc/src/boxed.rs:1694:9
       std::sys::unix::thread::Thread::new::thread_start
              at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/sys/unix/thread.rs:106:17
    9: start_thread
              at ./nptl/./nptl/pthread_create.c:477:8
   10: clone
              at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:95
 2022-05-03T20:58:38.100391Z ERROR Shutting down: thread 'Compactor thread' tenant_id: Some(ef5774ec9e5ca65b071a6da18713f91a), timeline_id: >
```

Now it appears during basebackup of green-base-273074 cluster too. There error prints the path of corrupted file. 

This is the output of dump_layerfile util for that file:
```
----- delta layer for ten 89df039475740a2e17fe091880d3e3b3 tli cbad1b55cb38740833d960cd1a910e38 keys 000000000000000000000000000000000000-FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF lsn 0/16C74A9-0/16C8529 ----
index_start_blk: 2, root 0
blk #0: path : prefix , suffix_len 26
  000000067f000032ac00004003000000000000000000016c83f0: 0000004001
  000000067f000032ac00004003000000000000000000016c8448: 000000444c
  000000067f000032ac00004003000000000000000000016c8500: 0000004516
  000000068000000000000004ec000000000000000000016c8180: 00000045df
  01000000000000000100000000000000000000000000016c81d8: 0000005f0a
  01000000000000000100000000000000000000000000016c8470: 0000005f34
  01000000000000000100000000000000000000000000016c8528: 0000005f5e
  03000000000000000000000000000000000100000000016c8180: 0000005f89
  key 000000067F000032AC000040030000000000 at 0/16C83F0:  rec 546 bytes will_init: true will_init: true, HEAP2 UNKNOWN_0x60
  key 000000067F000032AC000040030000000000 at 0/16C8448:  rec 100 bytes will_init: false will_init: false, HEAP HOT_UPDATE
  key 000000067F000032AC000040030000000000 at 0/16C8500:  rec 99 bytes will_init: false will_init: false, HEAP HOT_UPDATE
  key 000000068000000000000004EC0000000000 at 0/16C8180:  rec 3218 bytes will_init: true will_init: true, HEAP HOT_UPDATE
  key 010000000000000001000000000000000000 at 0/16C81D8:  DESERIALIZATION ERROR: deserialize error
  key 010000000000000001000000000000000000 at 0/16C8470:  DESERIALIZATION ERROR: deserialize error
  key 010000000000000001000000000000000000 at 0/16C8528:  DESERIALIZATION ERROR: deserialize error
  key 030000000000000000000000000000000001 at 0/16C8180:  img 88 bytes
```

**Comment by hlinnaka** [comment] 2022-05-04 18:03
What happened after the error, did the server recover?

**Comment by LizardWizzard** [comment] 2022-05-04 21:48
It restarted and there was no such error anymore. Also there was no tenant id there previously so I can find out what tenant it was. It might be connected to recently discovered corruption. Compaction loop failed at `deserialize error` somewhere in iterator over delta layer.

What I have on corruption:
Backtrace: https://gist.github.com/LizardWizzard/6875e7b099603d416346d7751314eae3
dump_layerfile output:
```
----- delta layer for ten 89df039475740a2e17fe091880d3e3b3 tli cbad1b55cb38740833d960cd1a910e38 keys 000000000000000000000000000000000000-FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF lsn 0/16C74A9-0/16C8529 ----
index_start_blk: 2, root 0
blk #0: path : prefix , suffix_len 26
  000000067f000032ac00004003000000000000000000016c83f0: 0000004001
  000000067f000032ac00004003000000000000000000016c8448: 000000444c
  000000067f000032ac00004003000000000000000000016c8500: 0000004516
  000000068000000000000004ec000000000000000000016c8180: 00000045df
  01000000000000000100000000000000000000000000016c81d8: 0000005f0a
  01000000000000000100000000000000000000000000016c8470: 0000005f34
  01000000000000000100000000000000000000000000016c8528: 0000005f5e
  03000000000000000000000000000000000100000000016c8180: 0000005f89
  key 000000067F000032AC000040030000000000 at 0/16C83F0:  rec 546 bytes will_init: true will_init: true, HEAP2 UNKNOWN_0x60
  key 000000067F000032AC000040030000000000 at 0/16C8448:  rec 100 bytes will_init: false will_init: false, HEAP HOT_UPDATE
  key 000000067F000032AC000040030000000000 at 0/16C8500:  rec 99 bytes will_init: false will_init: false, HEAP HOT_UPDATE
  key 000000068000000000000004EC0000000000 at 0/16C8180:  rec 3218 bytes will_init: true will_init: true, HEAP HOT_UPDATE
  key 010000000000000001000000000000000000 at 0/16C81D8:  DESERIALIZATION ERROR: deserialize error
  key 010000000000000001000000000000000000 at 0/16C8470:  DESERIALIZATION ERROR: deserialize error
  key 010000000000000001000000000000000000 at 0/16C8528:  DESERIALIZATION ERROR: deserialize error
  key 030000000000000000000000000000000001 at 0/16C8180:  img 88 bytes
```

I have no proof that these are relatetd but I think thats highly likely

**Comment by knizhnik** [comment] 2022-05-16 13:13
Can it be caused by commit [1fb3d0818] (optimization of BLOB length encoding?)

**Comment by knizhnik** [comment] 2022-05-16 17:07
Please notice that layer can be saved to S3 and so be older that this optimization was made.
Also storage format version was not incremented so it is not so trivial to check now whether layer has old or new format.

**Comment by dhammika** [comment] 2022-05-16 20:28
> Please notice that layer can be saved to S3 and so be older that this optimization was made. Also storage format version was not incremented so it is not so trivial to check now whether layer has old or new format.

Yes, a lot of things were on flight in staging around this time.

**Comment by stepashka** [comment] 2022-05-26 14:21
@LizardWizzard , do you know what's the status here?

**Comment by LizardWizzard** [comment] 2022-05-26 14:51
@stepashka A lot of bugs were found and fixed since this issue was opened. I think after merging #1735 we can close this issue for now

**Comment by bojanserafimov** [comment] 2022-06-29 16:31
@lubennikovaav ran into this when exporting basebackup from wild-smoke-235209, which is on very old stage pageserver (Mar 19 deployment). Is there a known fix to uncorrupt the data? Do we want to investigate?

**Comment by LizardWizzard** [comment] 2022-07-08 09:57
Is it the second staging pageserver or the first one? The problem was related to second one. First one has old storage and I think it is not worth it to investigate

**Comment by bojanserafimov** [comment] 2022-08-15 18:56
Time to close this? 0 occurences since the migration

**Closed** 2022-08-17 08:31 UTC
Labels: t/bug, c/storage/layered-repo
