### ISSUE TITLE
pageserver: assertion in `create_image_layer_for_metadata_keys`

### ISSUE THREAD

**Issue by jcsp** [neondatabase/neon#8277] opened 2024-07-05 11:13 UTC
Reproducer branch: https://github.com/neondatabase/neon/tree/jcsp/pg-regress-with-compaction

That branch is like https://github.com/neondatabase/neon/pull/8232, but with an extra explicit compaction step at the end of the test that generates full image layers.  That change can be pulled into the PR that fixes this bug, as a reproducer.

Running locally like this:
```
cargo build --release --features=testing && RUST_LOG=INFO DEFAULT_PG_VERSION=15 BUILD_TYPE=release scripts/pytest --timeout 600 -n32 -k "pg_regress[release-pg15-None]" 2>&1 | tee -i /tmp/test.log
```

(I recommend release mode for this test, otherwise it takes minutes to run)

The failure is like this:
```
 Error processing HTTP request: InternalServerError(create image layers

Caused by:
    Condition failed: `self.key_range.contains(&key)`

Stack backtrace:
   0: pageserver::tenant::storage_layer::image_layer::ImageLayerWriterInner::put_image::{{closure}}
             at /home/jcsp/neon/pageserver/src/tenant/storage_layer/image_layer.rs:811:9
      pageserver::tenant::storage_layer::image_layer::ImageLayerWriter::put_image::{{closure}}
             at /home/jcsp/neon/pageserver/src/tenant/storage_layer/image_layer.rs:950:63
   1: pageserver::tenant::timeline::Timeline::create_image_layer_for_metadata_keys::{{closure}}
             at /home/jcsp/neon/pageserver/src/tenant/timeline.rs:4438:53
      pageserver::tenant::timeline::Timeline::create_image_layers::{{closure}}::{{closure}}
             at /home/jcsp/neon/pageserver/src/tenant/timeline.rs:4577:22
   2: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /home/jcsp/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
      pageserver::tenant::timeline::Timeline::create_image_layers::{{closure}}
             at /home/jcsp/neon/pageserver/src/tenant/timeline.rs:4462:5
   3: pageserver::tenant::timeline::compaction::<impl pageserver::tenant::timeline::Timeline>::compact_legacy::{{closure}}
             at /home/jcsp/neon/pageserver/src/tenant/timeline/compaction.rs:140:22
```

**Comment by skyzh** [comment] 2024-07-05 14:45
This is caused by repl origin keys added in https://github.com/neondatabase/neon/pull/7099

```

Caused by:
    key_range=030000000000000000000000000000000003..630000000000000000000000000000000000, key=630000000000000000000000000000000001
```

still investigating

**Comment by skyzh** [comment] 2024-07-05 15:06
Likely caused by

```
            SparseKeySpace(KeySpace {
                ranges: vec![repl_origin_key_range(), Key::metadata_aux_key_range()],
            }),
```

not ordering the keyspaces in order.

Will add some debug_assertions. This should only affect people with inbound LR enabled, which we don't support for now.

**Comment by skyzh** [comment] 2024-07-05 15:22
fixed by https://github.com/neondatabase/neon/pull/8285

**Closed** 2024-07-08 13:05 UTC
Labels: t/bug, c/storage/pageserver, p/high
