### ISSUE TITLE
Visibility map corruption in regression test

### ISSUE THREAD

**Issue by hlinnaka** [neondatabase/neon#2807] opened 2022-11-14 14:11 UTC
From the CI at https://github.com/neondatabase/neon/actions/runs/3461746493:

```
diff -U3 /__w/neon/neon/vendor/postgres-v14/src/test/regress/expected/vacuum.out /tmp/test_output/test_pg_regress/regress/results/vacuum.out
--- /__w/neon/neon/vendor/postgres-v14/src/test/regress/expected/vacuum.out	2022-11-14 09:22:25.415936009 +0000
+++ /tmp/test_output/test_pg_regress/regress/results/vacuum.out	2022-11-14 13:58:31.145216464 +0000
@@ -148,6 +148,10 @@
 VACUUM no_index_cleanup;
 ALTER TABLE no_index_cleanup SET (vacuum_index_cleanup = auto);
 VACUUM no_index_cleanup;
+WARNING:  page is not marked all-visible but visibility map bit is set in relation "pg_toast_21703" page 6
+WARNING:  page is not marked all-visible but visibility map bit is set in relation "pg_toast_21703" page 7
+WARNING:  page is not marked all-visible but visibility map bit is set in relation "pg_toast_21703" page 8
+WARNING:  page is not marked all-visible but visibility map bit is set in relation "pg_toast_21703" page 9
 -- Parameter is set for both the parent table and its toast relation.
 INSERT INTO no_index_cleanup(i, t) VALUES (generate_series(31,60),
     repeat('1234567890',269));
```

**Comment by knizhnik** [comment] 2022-11-14 14:56
Is it any sense in investigating it without FSM/VM forks truncation fix (#2609)?

**Comment by hlinnaka** [comment] 2022-11-14 14:59
> Is it any sense in investigating it without FSM/VM forks truncation fix (https://github.com/neondatabase/neon/pull/2609)?

Not sure. I don't think these warnings should happen, with or without #2609. But that PR certainly changes things, so it wouldn't surprise me if it accidentally fixes this bug, too.

**Comment by arssher** [comment] 2022-12-02 17:52
Just happened again in unrelated PR:
https://neon-github-public-dev.s3.amazonaws.com/reports/pr-2733/debug/3602717284/index.html#suites/158be07438eb5188d40b466b6acfaeb3/a8820df7e4430c01/
https://github.com/neondatabase/neon/actions/runs/3602717284/jobs/6070319057

**Comment by knizhnik** [comment] 2022-12-03 17:58
I suspect that source of the problem is here:
```
				/*
				 * If data checksums are enabled (or wal_log_hints=on), we
				 * need to protect the heap page from being torn.
				 */
				if (XLogHintBitIsNeeded())
				{
					Page		heapPage = BufferGetPage(heapBuf);

					/* caller is expected to set PD_ALL_VISIBLE first */
					Assert(PageIsAllVisible(heapPage));
					PageSetLSN(heapPage, recptr);
				}
			}
```

We currently have `wal_log_hints=off` and so heap page will not be assigned LSN.
It means that last written lsn cache will not be updated for this and so old version of the page may be requested from pageserver (having no `PD_ALL_VISIBLE` flag set)

**Comment by knizhnik** [comment] 2022-12-04 08:37
Just 4 iteration of test_pg_regress.py are needed to reproduce this problem (in other test, but it seems to be doesn't matter).

**Comment by knizhnik** [comment] 2023-01-02 15:26
I have created PR with proposed fix and it is committed in main.
I believe that the problem is fixed. Let close the ticket and reopen it if the problem is reproduced once again.

**Closed** 2023-01-02 15:53 UTC
Labels: t/bug, c/storage/compute
