### ISSUE TITLE
`test_forward_compatibility@compatibility` is flaky

### ISSUE THREAD

**Issue by yeputons** [neondatabase/neon#2963] opened 2022-11-30 07:36 UTC
A recent failure in `main`: https://github.com/neondatabase/neon/actions/runs/3563254362/jobs/5986129088

`main` seems failing:passing about 50:50 at the moment, each failure is unique in its flakiness.

```

__________________________ test_forward_compatibility __________________________
[gw0] linux -- Python 3.9.2 /github/home/.cache/pypoetry/virtualenvs/neon-_pxWMzVK-py3.9/bin/python
subprocess.CalledProcessError: Command '['/tmp/neon-previous/bin/neon_local', 'pg', 'start', '--tenant-id', '325bbf12962a84e96cf57bcde7b95c22', '--pg-version', '14', '--port=15068', 'main']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:
test_runner/regress/test_compatibility.py:170: in test_forward_compatibility
    check_neon_works(
test_runner/regress/test_compatibility.py:311: in check_neon_works
    cli.pg_start("main", port=pg_port)
test_runner/fixtures/neon_fixtures.py:1661: in pg_start
    res = self.raw_cli(args)
test_runner/fixtures/neon_fixtures.py:1356: in raw_cli
    raise Exception(msg) from subprocess.CalledProcessError(
E   Exception:             Run ['/tmp/neon-previous/bin/neon_local', 'pg', 'start', '--tenant-id', '325bbf12962a84e96cf57bcde7b95c22', '--pg-version', '14', '--port=15068', 'main'] failed:
E                 stdout: Starting new postgres (v14) main on timeline 88760b3450f4dfb8bdca11cafed67536 ...
E   Extracting base backup to create postgres instance: path=/tmp/test_output/test_forward_compatibility/compatibility_snapshot/repo/pgdatadirs/tenants/325bbf12962a84e96cf57bcde7b95c22/main port=15068
E   Starting postgres node at 'host=127.0.0.1 port=15068 user=cloud_admin dbname=postgres'
E   
E                 stderr: command failed: pg_ctl failed, exit code: exit status: 1, stdout: waiting for server to start.... stopped waiting
E   , stderr: pg_ctl: could not start server
E   Examine the log output.
E   
E   
E   Stack backtrace:
E      0: control_plane::compute::PostgresNode::pg_ctl
E                at ./control_plane/src/compute.rs:453:13
E      1: control_plane::compute::PostgresNode::start
E                at ./control_plane/src/compute.rs:493:9
E      2: neon_local::handle_pg
E                at ./control_plane/src/bin/neon_local.rs:675:17
E      3: neon_local::main
E                at ./control_plane/src/bin/neon_local.rs:109:21
E      4: core::ops::function::FnOnce::call_once
E                at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/ops/function.rs:248:5
E         std::sys_common::backtrace::__rust_begin_short_backtrace
E                at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/sys_common/backtrace.rs:122:18
E      5: std::rt::lang_start::{{closure}}
E                at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/rt.rs:145:18
E      6: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
E                at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/ops/function.rs:280:13
E         std::panicking::try::do_call
E                at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:492:40
E         std::panicking::try
E                at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:456:19
E         std::panic::catch_unwind
E                at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panic.rs:137:14
E         std::rt::lang_start_internal::{{closure}}
E                at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/rt.rs:128:48
E         std::panicking::try::do_call
E                at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:492:40
E         std::panicking::try
E                at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:456:19
E         std::panic::catch_unwind
E                at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panic.rs:137:14
E         std::rt::lang_start_internal
E                at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/rt.rs:128:20
E      7: main
E      8: __libc_start_main
E      9: _start
------------------------------ Captured log setup ------------------------------
2022-11-28 09:26:30.699 INFO [neon_fixtures.py:2706] get_test_output_dir is /tmp/test_output/test_forward_compatibility
2022-11-28 09:26:30.699 INFO [neon_fixtures.py:2727] test_output_dir is /tmp/test_output/test_forward_compatibility
------------------------------ Captured log call -------------------------------
2022-11-28 09:26:30.700 INFO [test_compatibility.py:203] Copying snapshot from /tmp/test_output/test_create_snapshot/compatibility_snapshot_pg14 to /tmp/test_output/test_forward_compatibility/compatibility_snapshot
2022-11-28 09:26:31.461 INFO [neon_fixtures.py:1319] Running command "/tmp/neon-previous/bin/neon_local start"
2022-11-28 09:26:31.462 INFO [neon_fixtures.py:1320] Running in "/tmp/test_output/test_forward_compatibility/compatibility_snapshot/repo"
2022-11-28 09:26:32.185 INFO [neon_fixtures.py:1347] Run success: Starting etcd broker using "/usr/local/bin/etcd"
etcd started, pid: 14666
Starting pageserver at 'localhost:15060' in '/tmp/test_output/test_forward_compatibility/compatibility_snapshot/repo'.
pageserver started, pid: 14686
Starting safekeeper at '127.0.0.1:15063' in '/tmp/test_output/test_forward_compatibility/compatibility_snapshot/repo/safekeepers/sk1'.
safekeeper 1 started, pid: 14726
Starting safekeeper at '127.0.0.1:15065' in '/tmp/test_output/test_forward_compatibility/compatibility_snapshot/repo/safekeepers/sk2'.
safekeeper 2 started, pid: 14745
Starting safekeeper at '127.0.0.1:15067' in '/tmp/test_output/test_forward_compatibility/compatibility_snapshot/repo/safekeepers/sk3'.
safekeeper 3 started, pid: 14769

2022-11-28 09:26:32.186 INFO [neon_fixtures.py:1319] Running command "/tmp/neon-previous/bin/neon_local pg start --tenant-id 325bbf12962a84e96cf57bcde7b95c22 --pg-version 14 --port=15068 main"
2022-11-28 09:26:32.186 INFO [neon_fixtures.py:1320] Running in "/tmp/test_output/test_forward_compatibility/compatibility_snapshot/repo"
2022-11-28 09:26:32.402 INFO [neon_fixtures.py:1355]             Run ['/tmp/neon-previous/bin/neon_local', 'pg', 'start', '--tenant-id', '325bbf12962a84e96cf57bcde7b95c22', '--pg-version', '14', '--port=15068', 'main'] failed:
              stdout: Starting new postgres (v14) main on timeline 88760b3450f4dfb8bdca11cafed67536 ...
Extracting base backup to create postgres instance: path=/tmp/test_output/test_forward_compatibility/compatibility_snapshot/repo/pgdatadirs/tenants/325bbf12962a84e96cf57bcde7b95c22/main port=15068
Starting postgres node at 'host=127.0.0.1 port=15068 user=cloud_admin dbname=postgres'

              stderr: command failed: pg_ctl failed, exit code: exit status: 1, stdout: waiting for server to start.... stopped waiting
, stderr: pg_ctl: could not start server
Examine the log output.


Stack backtrace:
   0: control_plane::compute::PostgresNode::pg_ctl
             at ./control_plane/src/compute.rs:453:13
   1: control_plane::compute::PostgresNode::start
             at ./control_plane/src/compute.rs:493:9
   2: neon_local::handle_pg
             at ./control_plane/src/bin/neon_local.rs:675:17
   3: neon_local::main
             at ./control_plane/src/bin/neon_local.rs:109:21
   4: core::ops::function::FnOnce::call_once
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/ops/function.rs:248:5
      std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/sys_common/backtrace.rs:122:18
   5: std::rt::lang_start::{{closure}}
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/rt.rs:145:18
   6: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/ops/function.rs:280:13
      std::panicking::try::do_call
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:492:40
      std::panicking::try
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:456:19
      std::panic::catch_unwind
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panic.rs:137:14
      std::rt::lang_start_internal::{{closure}}
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/rt.rs:128:48
      std::panicking::try::do_call
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:492:40
      std::panicking::try
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:456:19
      std::panic::catch_unwind
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panic.rs:137:14
      std::rt::lang_start_internal
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/rt.rs:128:20
   7: main
   8: __libc_start_main
   9: _start
---------------------------- Captured log teardown -----------------------------
2022-11-28 09:26:32.602 INFO [neon_fixtures.py:1319] Running command "/tmp/neon-previous/bin/neon_local stop"
2022-11-28 09:26:32.603 INFO [neon_fixtures.py:1320] Running in "/tmp/test_output/test_forward_compatibility/compatibility_snapshot/repo"
2022-11-28 09:26:33.314 INFO [neon_fixtures.py:1347] Run success: Stopping pageserver with pid 14686 gracefully...
pageserver stopped
Stopping safekeeper 1 with pid 14726 gracefully...
safekeeper 1 stopped
Stopping safekeeper 2 with pid 14745 gracefully...
safekeeper 2 stopped
Stopping safekeeper 3 with pid 14769 gracefully...
safekeeper 3 stopped
Stopping etcd with pid 14666 immediately...
etcd stopped
```

**Comment by arssher** [comment] 2022-12-27 14:41
Interesting.
```
2022-11-28 09:26:32.272 GMT [14881] LOG:  starting with zenith basebackup at LSN 0/AB18AF8, prev 0/0
2022-11-28 09:26:32.272 GMT [14881] FATAL:  cannot start in read-write mode from this base backup
```

error in pg.log can only mean (IMV) that basebackup was taken not from the tip of the timeline (prev_lsn is not maintained then). However, this shouldn't be the case, and basebackup request confirms it
```
2022-11-28T09:26:32.195122Z  INFO handle_basebackup_request{tenant_id=325bbf12962a84e96cf57bcde7b95c22 timeline_id=88760b3450f4dfb8bdca11cafed67536 lsn=None prev_lsn=None full_backup=false}: taking basebackup lsn=0/AB18AF8, prev_lsn=0/0 (full_backup=false)
2022-11-28T09:26:32.204912Z  INFO handle_basebackup_request{tenant_id=325bbf12962a84e96cf57bcde7b95c22 timeline_id=88760b3450f4dfb8bdca11cafed67536 lsn=None prev_lsn=None full_backup=false lsn="0/AB18AF8"}: timeline.pg_version 14
2022-11-28T09:26:32.224773Z  INFO handle_basebackup_request{tenant_id=325bbf12962a84e96cf57bcde7b95c22 timeline_id=88760b3450f4dfb8bdca11cafed67536 lsn=None prev_lsn=None full_backup=false lsn="0/AB18AF8"}: basebackup complete
```

So I don't understand. Let's see if it repeats.

**Comment by koivunej** [comment] 2023-01-12 18:23
@arssher This happened again, see: https://neon-github-public-dev.s3.amazonaws.com/reports/pr-3315/release/3903582277/index.html#suites/0fbaeb107ef328d03993d44a1fb15690/d7e5d24ebc8f1c75/

Review result: clearly unrelated to the PR #3315.

pg logs:

```
2023-01-12 15:34:55.341 GMT [13873] LOG:  starting with zenith basebackup at LSN 0/AA31D80, prev 0/0
2023-01-12 15:34:55.341 GMT [13873] FATAL:  cannot start in read-write mode from this base backup
```

**Comment by koivunej** [comment] 2023-01-24 09:42
Again with #3419: https://neon-github-public-dev.s3.amazonaws.com/reports/pr-3419/release/3994470974/index.html#suites/0fbaeb107ef328d03993d44a1fb15690/ad2c872528d2ee46/

**Comment by kelvich** [comment] 2023-03-06 21:56
And again in #3703 https://neon-github-public-dev.s3.amazonaws.com/reports/pr-3703/debug/4348163542/index.html#suites/0fbaeb107ef328d03993d44a1fb15690/35839f6f0e5d9c3c/

**Comment by arssher** [comment] 2023-03-07 17:50
And again
https://neon-github-public-dev.s3.amazonaws.com/reports/pr-3759/debug/4356441932/index.html#categories

**Comment by kelvich** [comment] 2023-03-07 18:26
I got it three times with https://github.com/neondatabase/neon/pull/3703 I guess it may have changed some timings to make failure more probable.

I quickly looked at the code and things looked sketchy -- seems that we get invalidlsn in basebackup in non-init mode, not sure is it okay now or not. @knizhnik do you remeber what is the last iteration with that prev-lsn?

**Comment by arssher** [comment] 2023-03-08 04:58
AFAIR we don't maintain prev_lsn for non latest point. So this invalid prev_lsn is ok in case of backup from the past, but basebackup request at lsn=None (latest) should have valid prev_lsn, and test failure violates that.

**Comment by koivunej** [comment] 2023-03-10 16:07
Once more: https://neon-github-public-dev.s3.amazonaws.com/reports/pr-3790/debug/4384985320/index.html#suites/0fbaeb107ef328d03993d44a1fb15690/9b2e4975b3ace73d/ -- similar to what I've reported earlier.

**Comment by koivunej** [comment] 2023-03-14 12:28
Still reproduces on main:

```
2023-03-14 11:28:25.181 GMT [69087] LOG:  starting with zenith basebackup at LSN 0/AB409C8, prev 0/0
2023-03-14 11:28:25.182 GMT [69087] FATAL:  cannot start in read-write mode from this base backup
```

https://neon-github-public-dev.s3.amazonaws.com/reports/main/debug/4415125743/index.html#suites/0fbaeb107ef328d03993d44a1fb15690/fff19da993142560/

**Comment by koivunej** [comment] 2023-03-16 11:34
Once more: https://neon-github-public-dev.s3.amazonaws.com/reports/main/debug/4435279198/index.html#suites/0fbaeb107ef328d03993d44a1fb15690/ffe215e81a4c7b99/

```
2023-03-16 09:13:17.918 GMT [70801] LOG:  starting with zenith basebackup at LSN 0/AB30FC8, prev 0/0
2023-03-16 09:13:17.918 GMT [70801] FATAL:  cannot start in read-write mode from this base backup
```

Will not be reporting this anymore since we have already confirmed updating the binaries did not change the situation.

**Comment by problame** [comment] 2023-03-20 14:31
This failure looks different from the above:

```
2023-03-20 14:22:49.737 GMT [65445] LOG:  starting with zenith basebackup at LSN 0/AB898D0, prev 0/AB89890
```

https://neon-github-public-dev.s3.amazonaws.com/reports/pr-3837/debug/4469175202/index.html#suites/0fbaeb107ef328d03993d44a1fb15690/a70289fb8c99e914/

**Comment by arssher** [comment] 2023-03-22 20:20
I'm suspicious on this comment:
https://github.com/neondatabase/neon/blob/main/pageserver/src/tenant/metadata.rs#L61
Does this mean if we restart pageserver with some data in memory not flushed, we lose prev_record_lsn? CC @SomeoneToIgnore

**Comment by arssher** [comment] 2023-03-28 07:14
What I think happens here:
- Flushing of frozen layer (`flush_frozen_layer`) doesn't prevent further data writes (which is good). So when it is completed and metadata file is updated (`update_metadata_file`), `last_record_lsn` could have gone farther, and so `prev_record_lsn` for the fresh `disk_consistent_lsn` is not available. In `test_create_snapshot` we `timeline_checkpoint` the pageserver and terminate the compute soon, so normally test passes, but small amount of WAL always has a chance to be generated in the middle -- xl_running_xacts, VACUUM, etc, in which case it fails.
- So, after pageserver restart (in this test, when we start prepared snapshot) `prev_record_lsn` is invalid.
- Now, generally it shouldn't be a problem, because if there is a range of WAL committed after checkpoint on pageserver,  pageserver will (re)consume it soon from safekeepers. Normally, compute on start runs sync-safekeepers to learn the real end of committed WAL and carries this LSN in the basebackup request, forcing waiting if needed. However, there is a bug in neon_local: `ComputeControlPlane::new_node` sets `uses_wal_proposer=false` which disables sync-safekeepers -- basebackup request has `None` lsn, so pageserver returns what it currently has. I'll fix that.

**Closed** 2023-03-31 12:15 UTC
Labels: a/test/flaky
