### ISSUE TITLE
Postgres unable able to start with "waiting for WAL to become available at 0/B5002000" message

### ISSUE THREAD

**Issue by mingfang** [neondatabase/neon#4107] opened 2023-04-28 13:03 UTC
My local install is failing to restart.
The log keeps printing this message.
```
waiting for WAL to become available at 0/B5002000
```

The tenant and time status seems fine.
```
{
    "current_physical_size": 4045045760,
    "has_in_progress_downloads": false,
    "id": "ca5fbf3053bc9ea10eb2f32949f78c91",
    "state": {
        "slug": "Active"
    }
}
```

```
{
    "ancestor_lsn": null,
    "ancestor_timeline_id": null,
    "current_logical_size": 814563328,
    "current_logical_size_non_incremental": null,
    "current_physical_size": 4045045760,
    "disk_consistent_lsn": "0/B5480B40",
    "last_received_msg_lsn": null,
    "last_received_msg_ts": null,
    "last_record_lsn": "0/B5480B40",
    "latest_gc_cutoff_lsn": "0/4129838",
    "pg_version": 15,
    "prev_record_lsn": "0/0",
    "remote_consistent_lsn": "0/B5480B40",
    "state": "Active",
    "tenant_id": "ca5fbf3053bc9ea10eb2f32949f78c91",
    "timeline_dir_layer_file_size_sum": null,
    "timeline_id": "80ed3be9cbb1a738d90ff39e7e4ccaaa",
    "wal_source_connstr": null
}
```
I tried restarting everything, safekeepers, pageserver and postgres but still can not get it to work.

**Comment by koivunej** [comment] 2023-06-01 13:08
@mingfang do you have some way of reproducing this issue, or logs?

> `"wal_source_connstr": null`

was a safekeeper running when this happened?

**Comment by mingfang** [comment] 2023-06-01 14:03
@koivunej
Thanks for looking into this.
This usually happens whenever I upgrade the entire stack.
My steps are
1-upgrade the three safekeepers one at a time
2-upgrade pageserver
3-attach tenant and timeline to pageserver
4-upgrade postgres

Not sure if that's the right sequence.
Perhaps I should take down the postgres before upgrading the pageserver.

The good news is I upgraded to the latest yesterday and the problem went away.
I'll try to repeat this several times to confirm if this doesn't come back.

**Comment by hlinnaka** [comment] 2024-06-11 19:10
I guess whatever the problem was, it no longer occurs. Closing.

**Closed by hlinnaka** 2024-06-11 19:10 UTC
Labels: t/bug, c/storage/pageserver, triaged
