### ISSUE TITLE
`test_detach_while_attaching[real_s3]` is flaky

### ISSUE THREAD

**Issue by yeputons** [neondatabase/neon#2980] opened 2022-12-01 00:48 UTC
Run: https://github.com/neondatabase/neon/actions/runs/3586194149/jobs/6035238423

```
__________ ERROR at teardown of test_detach_while_attaching[real_s3] ___________
[gw2] linux -- Python 3.9.2 /github/home/.cache/pypoetry/virtualenvs/neon-_pxWMzVK-py3.9/bin/python
/github/home/.cache/pypoetry/virtualenvs/neon-_pxWMzVK-py3.9/lib/python3.9/site-packages/allure_commons/_allure.py:200: in __call__
    return self._fixture_function(*args, **kwargs)
test_runner/fixtures/neon_fixtures.py:1043: in neon_env_builder
    yield builder
test_runner/fixtures/neon_fixtures.py:785: in __exit__
    self.env.pageserver.assert_no_errors()
test_runner/fixtures/neon_fixtures.py:1843: in assert_no_errors
    assert not errors
E   assert not ["2022-11-30T19:09:13.923544Z ERROR remote_upload{tenant=8b851d39ea5d38ba9b247e50ae353af8 timeline=b3e25ee1ae4b36b00eb... (attempt 0): Failed to upload index part for '8b851d39ea5d38ba9b247e50ae353af8 / b3e25ee1ae4b36b00ebac1b3ff090b64'\n"]
------------------------------ Captured log setup ------------------------------
2022-11-30 19:08:36.346 INFO [neon_fixtures.py:2715] get_test_output_dir is /tmp/test_output/test_detach_while_attaching[real_s3]
2022-11-30 19:08:36.347 INFO [neon_fixtures.py:2736] test_output_dir is /tmp/test_output/test_detach_while_attaching[real_s3]
------------------------------ Captured log call -------------------------------
2022-11-30 19:08:36.477 INFO [neon_fixtures.py:910] Config: 
default_tenant_id = '8b851d39ea5d38ba9b247e50ae353af8'

[etcd_broker]
broker_endpoints = ['http://127.0.0.1:17001/']
etcd_binary_path = '/usr/local/bin/etcd'

[pageserver]
id=1
listen_pg_addr = 'localhost:17112'
listen_http_addr = 'localhost:17113'
auth_type = 'Trust'

[[safekeepers]]
id = 1
pg_port = 17114
http_port = 17115
sync = false
2022-11-30 19:08:36.478 INFO [neon_fixtures.py:1319] Running command "/tmp/neon/bin/neon_local init --config=/tmp/tmpav13umgr --pg-version 14 --pageserver-config-override=remote_storage={bucket_name='ci-tests-s3',            bucket_region='us-west-2',prefix_in_bucket='2587e4e7-c1ab-42da-a8a3-89403a6e6daa/test_detach_while_attaching'}"
2022-11-30 19:08:36.478 INFO [neon_fixtures.py:1320] Running in "/tmp/test_output/test_detach_while_attaching[real_s3]/repo"
2022-11-30 19:08:38.612 INFO [neon_fixtures.py:1347] Run success: Starting pageserver at 'localhost:17112' in '/tmp/test_output/test_detach_while_attaching[real_s3]/repo'.
pageserver started, pid: 26329
Successfully initialized timeline b3e25ee1ae4b36b00ebac1b3ff090b64
Stopped pageserver 1 process with pid 26329

2022-11-30 19:08:38.613 INFO [neon_fixtures.py:1319] Running command "/tmp/neon/bin/neon_local pageserver start --pageserver-config-override=remote_storage={bucket_name='ci-tests-s3',            bucket_region='us-west-2',prefix_in_bucket='2587e4e7-c1ab-42da-a8a3-89403a6e6daa/test_detach_while_attaching'}"
2022-11-30 19:08:38.613 INFO [neon_fixtures.py:1320] Running in "/tmp/test_output/test_detach_while_attaching[real_s3]/repo"
2022-11-30 19:08:38.726 INFO [neon_fixtures.py:1347] Run success: Starting pageserver at 'localhost:17112' in '/tmp/test_output/test_detach_while_attaching[real_s3]/repo'.
pageserver started, pid: 26506

2022-11-30 19:08:38.726 INFO [neon_fixtures.py:1319] Running command "/tmp/neon/bin/neon_local safekeeper start 1"
2022-11-30 19:08:38.726 INFO [neon_fixtures.py:1320] Running in "/tmp/test_output/test_detach_while_attaching[real_s3]/repo"
2022-11-30 19:08:38.840 INFO [neon_fixtures.py:1347] Run success: Starting safekeeper at '127.0.0.1:17114' in '/tmp/test_output/test_detach_while_attaching[real_s3]/repo/safekeepers/sk1'.
safekeeper 1 started, pid: 26544

2022-11-30 19:08:38.844 INFO [neon_fixtures.py:1319] Running command "/tmp/neon/bin/neon_local pg create --tenant-id 8b851d39ea5d38ba9b247e50ae353af8 --branch-name main --pg-version 14 --port 17116 main_pg_node"
2022-11-30 19:08:38.844 INFO [neon_fixtures.py:1320] Running in "/tmp/test_output/test_detach_while_attaching[real_s3]/repo"
2022-11-30 19:08:38.856 INFO [neon_fixtures.py:1347] Run success: 
2022-11-30 19:08:38.857 INFO [neon_fixtures.py:2262] Starting postgres node main_pg_node
2022-11-30 19:08:38.857 INFO [neon_fixtures.py:1319] Running command "/tmp/neon/bin/neon_local pg start --tenant-id 8b851d39ea5d38ba9b247e50ae353af8 --pg-version 14 --port=17116 main_pg_node"
2022-11-30 19:08:38.857 INFO [neon_fixtures.py:1320] Running in "/tmp/test_output/test_detach_while_attaching[real_s3]/repo"
2022-11-30 19:08:39.418 INFO [neon_fixtures.py:1347] Run success: Starting existing postgres main_pg_node...
Safekeepers synced on 0/0
Extracting base backup to create postgres instance: path=/tmp/test_output/test_detach_while_attaching[real_s3]/repo/pgdatadirs/tenants/8b851d39ea5d38ba9b247e50ae353af8/main_pg_node port=17116
Starting postgres node at 'host=127.0.0.1 port=17116 user=cloud_admin dbname=postgres'

2022-11-30 19:08:39.419 INFO [neon_fixtures.py:2377] Postgres startup took 0.5749826431274414 seconds
2022-11-30 19:08:39.441 INFO [neon_fixtures.py:408] Executing query: show neon.tenant_id
2022-11-30 19:08:39.446 INFO [neon_fixtures.py:408] Executing query: show neon.timeline_id
2022-11-30 19:08:40.157 INFO [neon_fixtures.py:2951] waiting for last_record_lsn to reach 0/20C2860, now 0/1C55A28, iteration 1
2022-11-30 19:08:41.161 INFO [neon_fixtures.py:1251] Requesting checkpoint: tenant 8b851d39ea5d38ba9b247e50ae353af8, timeline b3e25ee1ae4b36b00ebac1b3ff090b64
2022-11-30 19:08:43.400 INFO [neon_fixtures.py:1255] Got checkpoint request response code: 200
2022-11-30 19:08:43.400 INFO [test_tenant_detach.py:144] waiting for upload
2022-11-30 19:08:43.403 INFO [test_tenant_detach.py:148] upload is done
2022-11-30 19:08:43.579 INFO [neon_fixtures.py:1081] Requesting config failpoints: [('attach-before-activate', 'return(5000)')]
2022-11-30 19:08:43.581 INFO [neon_fixtures.py:1087] Got failpoints request response code 200
---------------------------- Captured log teardown -----------------------------
2022-11-30 19:09:17.216 INFO [neon_fixtures.py:777] Cleaning up all storage and compute nodes
2022-11-30 19:09:17.216 INFO [neon_fixtures.py:1319] Running command "/tmp/neon/bin/neon_local pg stop --tenant-id 8b851d39ea5d38ba9b247e50ae353af8 main_pg_node"
2022-11-30 19:09:17.216 INFO [neon_fixtures.py:1320] Running in "/tmp/test_output/test_detach_while_attaching[real_s3]/repo"
2022-11-30 19:09:17.658 INFO [neon_fixtures.py:1347] Run success: 
2022-11-30 19:09:17.659 INFO [neon_fixtures.py:2494] Stopping safekeeper 1
2022-11-30 19:09:17.659 INFO [neon_fixtures.py:1319] Running command "/tmp/neon/bin/neon_local safekeeper stop 1 -m immediate"
2022-11-30 19:09:17.659 INFO [neon_fixtures.py:1320] Running in "/tmp/test_output/test_detach_while_attaching[real_s3]/repo"
2022-11-30 19:09:17.919 INFO [neon_fixtures.py:1347] Run success: Stopping safekeeper 1 with pid 26544 immediately...
safekeeper 1 stopped

2022-11-30 19:09:17.919 INFO [neon_fixtures.py:1590] Stopping pageserver with ['pageserver', 'stop', '-m', 'immediate']
2022-11-30 19:09:17.919 INFO [neon_fixtures.py:1319] Running command "/tmp/neon/bin/neon_local pageserver stop -m immediate"
2022-11-30 19:09:17.919 INFO [neon_fixtures.py:1320] Running in "/tmp/test_output/test_detach_while_attaching[real_s3]/repo"
2022-11-30 19:09:18.191 INFO [neon_fixtures.py:1347] Run success: Stopping pageserver with pid 26506 immediately...
pageserver stopped

2022-11-30 19:09:18.191 INFO [neon_fixtures.py:729] removing data from test s3 bucket ci-tests-s3 by prefix 2587e4e7-c1ab-42da-a8a3-89403a6e6daa/test_detach_while_attaching
2022-11-30 19:09:19.114 INFO [neon_fixtures.py:764] deleted 0 objects from remote storage
```

**Comment by arssher** [comment] 2022-12-03 07:11
duplicate of 
https://github.com/neondatabase/neon/issues/2990

**Closed by arssher** 2022-12-03 07:11 UTC
Labels: a/test/flaky
